version: '3'

services:

  nginx:
    image: nginx
    links:
      - corpora:corpora
      - iiif:iiif
    volumes:
      - ./nginx/corpora.conf:/etc/nginx/conf.d/default.conf
      - /Users/bptarpley/corpora:/data/corpora
    ports:
      - 80:80

  corpora:
    build: ./app
    command: ./start.sh
    environment:
      CRP_HOST: localhost
      CRP_MONGO_HOST: mongo
      CRP_MONGO_DB: corpora
      CRP_MONGO_USER: corpora
      CRP_MONGO_PWD: corpora
      CRP_MONGO_POOLSIZE: 5
      CRP_NEO4J_HOST: neo4j:7687
      CRP_NEO4J_USER: neo4j
      CRP_NEO4J_PWD: j4neo
      CRP_ELASTIC_HOST: elastic
      CRP_DJANGO_WORKERS: 3
      CRP_HUEY_WORKERS: 10
      CRP_EMOP_HOST: dh-db01.tamu.edu
      CRP_EMOP_DB: emop_dashboard
      CRP_EMOP_USER: emop_dashboard
      CRP_EMOP_PWD: 3ed446ba64709c99c224
      CRP_USE_SSL: "no"
      GOOGLE_APPLICATION_CREDENTIALS: /etc/google/creds.json
    volumes:
      - ./app:/apps/corpora
      - ./app/imagemagick.xml:/etc/ImageMagick-6/policy.xml
      - /Users/bptarpley/corpora/static:/static
      - /Users/bptarpley/corpora/corpora:/corpora
      - /Users/bptarpley/corpora/import:/import
      - ./gcv_creds.json:/etc/google/creds.json:ro
    depends_on:
      - mongo
      - neo4j
      - elastic
      - redis
    links:
      - redis:redis
      - mongo:mongo
      - neo4j:neo4j
      - elastic:elastic

  redis:
    image: redis:5.0.4

  iiif:
    image: pulibrary/cantaloupe
    volumes:
      - /Users/bptarpley/corpora/corpora:/var/lib/cantaloupe/images/corpora
      - ./iiif/cantaloupe.properties:/etc/cantaloupe.properties

  mongo:
    image: mongo:3.4-xenial
    environment:
      MONGO_INITDB_ROOT_USERNAME: corpora
      MONGO_INITDB_ROOT_PASSWORD: corpora
    volumes:
      - /Users/bptarpley/corpora/archive:/data/db
    ports:
      - 27017:27017

  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_dbms_memory_pagecache_size: 512M
      NEO4J_dbms_memory_heap_max__size: 512M
      NEO4J_AUTH: neo4j/j4neo
    volumes:
      - /Users/bptarpley/corpora/link:/data
    ports:
      - 7687:7687
      - 7474:7474

  elastic:
    image: elasticsearch:7.4.0
    environment:
      discovery.type: single-node
    volumes:
      - /Users/bptarpley/corpora/search:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
