REGISTRY = [
    {
        "name": "Play",
        "plural_name": "Plays",
        "fields": [
            {
                "name": "title",
                "label": "Title",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "prefix",
                "label": "NVS Prefix",
                "indexed": False,
                "unique": True,
                "multiple": False,
                "in_lists": True,
                "type": "keyword",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "base_text",
                "label": "Base Text",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "cross_reference",
                "choices": [],
                "cross_reference_type": "Document",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "primary_witnesses",
                "label": "Primary Witnesses",
                "indexed": False,
                "unique": False,
                "multiple": True,
                "in_lists": True,
                "type": "cross_reference",
                "choices": [],
                "cross_reference_type": "Document",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "genre",
                "label": "Genre",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "keyword",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            }
        ],
        "show_in_nav": True,
        "proxy_field": "",
        "templates": {
            "Label": {
                "template": "{{ Play.title }}",
                "mime_type": "text/html"
            }
        },
        "inherited": False,
        "invalid_field_names": [
            "corpus_id",
            "content_type",
            "last_updated",
            "provenance",
            "path",
            "label",
            "uri"
        ]
    },
    {
        "name": "ContentBlock",
        "plural_name": "Content Blocks",
        "fields": [
            {
                "name": "handle",
                "label": "Handle",
                "indexed": False,
                "unique": True,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "html",
                "label": "HTML",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "html",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "play",
                "label": "Play",
                "indexed": True,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "cross_reference",
                "choices": [],
                "cross_reference_type": "Play",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            }
        ],
        "show_in_nav": True,
        "proxy_field": "",
        "templates": {
            "Label": {
                "template": "{{ ContentBlock.handle }}",
                "mime_type": "text/html"
            }
        },
        "inherited": False,
        "invalid_field_names": [
            "corpus_id",
            "content_type",
            "path",
            "label",
            "uri",
            "last_updated",
            "provenance"
        ]
    },
    {
        "name": "DocumentCollection",
        "plural_name": "Document Collections",
        "fields": [
            {
                "name": "siglum",
                "label": "Siglum",
                "indexed": False,
                "unique": True,
                "multiple": False,
                "in_lists": True,
                "type": "keyword",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "siglum_label",
                "label": "Siglum Label",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "keyword",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "referenced_documents",
                "label": "Referenced Documents",
                "indexed": False,
                "unique": False,
                "multiple": True,
                "in_lists": True,
                "type": "cross_reference",
                "choices": [],
                "cross_reference_type": "Document",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            }
        ],
        "show_in_nav": True,
        "proxy_field": "",
        "templates": {
            "Label": {
                "template": "{{ DocumentCollection.siglum_label }}",
                "mime_type": "text/html"
            }
        },
        "inherited": False,
        "invalid_field_names": [
            "corpus_id",
            "content_type",
            "path",
            "label",
            "uri",
            "last_updated",
            "provenance"
        ]
    },
    {
        "name": "WitnessLocation",
        "plural_name": "Witness Locations",
        "fields": [
            {
                "name": "witness",
                "label": "Witness",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "cross_reference",
                "choices": [],
                "cross_reference_type": "Document",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "starting_page",
                "label": "Starting Page",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "keyword",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "starting_line",
                "label": "Starting Line",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "keyword",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "ending_page",
                "label": "Ending Page",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "keyword",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "ending_line",
                "label": "Ending Line",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "keyword",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            }
        ],
        "show_in_nav": True,
        "proxy_field": "",
        "templates": {
            "Label": {
                "template": "{{ WitnessLocation.witness.siglum_label }} {{ WitnessLocation.starting_page }}{% if WitnessLocation.starting_line %}:{{ WitnessLocation.starting_line }}{% endif %}{% if WitnessLocation.ending_page %} - {{ WitnessLocation.ending_page }}{% endif %}{% if WitnessLocation.ending_line %}:{{ WitnessLocation.ending_line }}{% endif %}",
                "mime_type": "text/html"
            }
        },
        "inherited": False,
        "invalid_field_names": [
            "corpus_id",
            "content_type",
            "path",
            "label",
            "uri",
            "last_updated",
            "provenance"
        ]
    },
    {
        "name": "PlayLine",
        "plural_name": "Play Lines",
        "fields": [
            {
                "name": "xml_id",
                "label": "XML ID",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "line_label",
                "label": "Line Label",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "line_number",
                "label": "Line Number",
                "indexed": False,
                "unique": True,
                "multiple": False,
                "in_lists": True,
                "type": "number",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "act",
                "label": "Act",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "scene",
                "label": "Scene",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "witness_locations",
                "label": "Witness Locations",
                "indexed": False,
                "unique": False,
                "multiple": True,
                "in_lists": True,
                "type": "cross_reference",
                "choices": [],
                "cross_reference_type": "WitnessLocation",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "text",
                "label": "Text",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "rendered_html",
                "label": "Rendered HTML",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "html",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "witness_meter",
                "label": "Witness Meter",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": False,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "play",
                "label": "Play",
                "indexed": True,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "cross_reference",
                "choices": [],
                "cross_reference_type": "Play",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            }
        ],
        "show_in_nav": True,
        "proxy_field": "",
        "templates": {
            "Label": {
                "template": "[{{ PlayLine.line_number }}] {{ PlayLine.words|join:' ' }}",
                "mime_type": "text/html"
            }
        },
        "inherited": False,
        "invalid_field_names": [
            "corpus_id",
            "content_type",
            "path",
            "label",
            "uri",
            "last_updated",
            "provenance"
        ]
    },
    {
        "name": "PlayTag",
        "plural_name": "Play Tags",
        "fields": [
            {
                "name": "name",
                "label": "Name",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "classes",
                "label": "Classes",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "start_location",
                "label": "Starting Location",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "decimal",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "end_location",
                "label": "Ending Location",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "decimal",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "play",
                "label": "Play",
                "indexed": True,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "cross_reference",
                "choices": [],
                "cross_reference_type": "Play",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            }
        ],
        "show_in_nav": True,
        "proxy_field": "",
        "templates": {
            "Label": {
                "template": "[{{ PlayTag.name }} class=\"{{ PlayTag.classes }}\"]",
                "mime_type": "text/html"
            }
        },
        "inherited": False,
        "invalid_field_names": [
            "corpus_id",
            "content_type",
            "path",
            "label",
            "uri",
            "last_updated",
            "provenance"
        ]
    },
    {
        "name": "TextualVariant",
        "plural_name": "Textual Variants",
        "fields": [
            {
                "name": "lemma",
                "label": "Lemma",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "transform_type",
                "label": "Transform Type",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "keyword",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "transform",
                "label": "Transform",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "description",
                "label": "Description",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "variant",
                "label": "Variant",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "witness_formula",
                "label": "Witness Formula",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "html",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "witnesses",
                "label": "Witnesses",
                "indexed": False,
                "unique": False,
                "multiple": True,
                "in_lists": True,
                "type": "cross_reference",
                "choices": [],
                "cross_reference_type": "Document",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "witness_meter",
                "label": "Witness Meter",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "html",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "has_bug",
                "label": "Has Bug?",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "number",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "play",
                "label": "Play",
                "indexed": True,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "cross_reference",
                "choices": [],
                "cross_reference_type": "Play",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            }
        ],
        "show_in_nav": True,
        "proxy_field": "",
        "templates": {
            "Label": {
                "template": "{% if TextualVariant.has_bug %}<span style='background-color: red; color: white;'>{% endif %}{% if TextualVariant.lemma %}<b>Lemma:</b> {{ TextualVariant.lemma }} {% endif %}{% if TextualVariant.transform_type %}<b>Transform Type:</b> {{ TextualVariant.transform_type }} {% endif %}{% if TextualVariant.transform %}<b>Transform:</b> {{ TextualVariant.transform }} {% endif %}{% if TextualVariant.description %}<b>Description:</b> {{ TextualVariant.description }} {% endif %}{% if TextualVariant.variant %}<b>Result:</b> {{ TextualVariant.variant }}{% endif %} ({% for witness in TextualVariant.witnesses %}{{ witness.label|safe }}{% if not forloop.last %}, {% endif %}{% endfor %}){% if TextualVariant.has_bug %}</span>{% endif %}",
                "mime_type": "text/html"
            }
        },
        "inherited": False,
        "invalid_field_names": [
            "corpus_id",
            "content_type",
            "path",
            "label",
            "uri",
            "last_updated",
            "provenance"
        ]
    },
    {
        "name": "TextualNote",
        "plural_name": "Textual Notes",
        "fields": [
            {
                "name": "xml_id",
                "label": "XML ID",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "lines",
                "label": "Lines",
                "indexed": False,
                "unique": False,
                "multiple": True,
                "in_lists": True,
                "type": "cross_reference",
                "choices": [],
                "cross_reference_type": "PlayLine",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "variants",
                "label": "Variants",
                "indexed": False,
                "unique": False,
                "multiple": True,
                "in_lists": True,
                "type": "cross_reference",
                "choices": [],
                "cross_reference_type": "TextualVariant",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "witness_meter",
                "label": "Witness Meter",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": False,
                "type": "html",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "play",
                "label": "Play",
                "indexed": True,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "cross_reference",
                "choices": [],
                "cross_reference_type": "Play",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            }
        ],
        "show_in_nav": True,
        "proxy_field": "",
        "templates": {
            "Label": {
                "template": "TextualNote {{ TextualNote.id }}",
                "mime_type": "text/html"
            }
        },
        "inherited": False,
        "invalid_field_names": [
            "corpus_id",
            "content_type",
            "path",
            "label",
            "uri",
            "last_updated",
            "provenance"
        ]
    },
    {
        "name": "Commentary",
        "plural_name": "Commentaries",
        "fields": [
            {
                "name": "xml_id",
                "label": "XML ID",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "lines",
                "label": "Lines",
                "indexed": False,
                "unique": False,
                "multiple": True,
                "in_lists": True,
                "type": "cross_reference",
                "choices": [],
                "cross_reference_type": "PlayLine",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "line_label",
                "label": "Line Label",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "subject_matter",
                "label": "Subject Matter",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "contents",
                "label": "Contents",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "html",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "play",
                "label": "Play",
                "indexed": True,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "cross_reference",
                "choices": [],
                "cross_reference_type": "Play",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            }
        ],
        "show_in_nav": True,
        "proxy_field": "",
        "templates": {
            "Label": {
                "template": "Commentary {{ Commentary.id }}",
                "mime_type": "text/html"
            }
        },
        "inherited": False,
        "invalid_field_names": [
            "corpus_id",
            "content_type",
            "path",
            "label",
            "uri",
            "last_updated",
            "provenance"
        ]
    },
    {
        "name": "Document",
        "plural_name": "Documents",
        "fields": [
            {
                "name": "title",
                "label": "Title",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": True
            },
            {
                "name": "author",
                "label": "Author",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": True
            },
            {
                "name": "work",
                "label": "Work",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": False,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": True
            },
            {
                "name": "expression",
                "label": "Expression",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": False,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": True
            },
            {
                "name": "manifestation",
                "label": "Manifestation",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": False,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": True
            },
            {
                "name": "pub_date",
                "label": "Published",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "keyword",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": True
            },
            {
                "name": "files",
                "label": "Files",
                "indexed": False,
                "unique": False,
                "multiple": True,
                "in_lists": False,
                "type": "embedded",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": True
            },
            {
                "name": "pages",
                "label": "Pages",
                "indexed": False,
                "unique": False,
                "multiple": True,
                "in_lists": False,
                "type": "embedded",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": True
            },
            {
                "name": "page_sets",
                "label": "Page Sets",
                "indexed": False,
                "unique": False,
                "multiple": True,
                "in_lists": False,
                "type": "embedded",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": True
            },
            {
                "name": "editor",
                "label": "Editor(s)",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "publisher",
                "label": "Publisher",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "place",
                "label": "Place of Publication",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "siglum",
                "label": "Siglum",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "keyword",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "siglum_label",
                "label": "Siglum Label",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "keyword",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "bibliographic_entry",
                "label": "Bibliographic Entry",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": False,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "nvs_doc_type",
                "label": "Document Type",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "keyword",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            }
        ],
        "show_in_nav": True,
        "proxy_field": "",
        "templates": {
            "Label": {
                "template": "{{ Document.siglum_label|safe }}",
                "mime_type": "text/html"
            }
        },
        "inherited": True,
        "invalid_field_names": [
            "has_primary_text",
            "corpus_id",
            "content_type",
            "path",
            "label",
            "uri",
            "last_updated",
            "provenance",
            "save_page",
            "ordered_pages",
            "save_file",
            "kvp",
            "running_jobs",
            "get_page_file_collection",
            "page_file_collections",
            "save_page_file"
        ]
    },
    {
        "name": "Character",
        "plural_name": "Characters",
        "fields": [
            {
                "name": "name",
                "label": "Name",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "keyword",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "role",
                "label": "Role",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "text",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "xml_id",
                "label": "XML ID",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "keyword",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "external_uri",
                "label": "External URI",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "keyword",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "speaker_abbreviations",
                "label": "Speaker Abbreviations",
                "indexed": False,
                "unique": False,
                "multiple": True,
                "in_lists": True,
                "type": "keyword",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "play",
                "label": "Play",
                "indexed": True,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "cross_reference",
                "choices": [],
                "cross_reference_type": "Play",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            }
        ],
        "show_in_nav": True,
        "proxy_field": "",
        "templates": {
            "Label": {
                "template": "{{ Character.name }}",
                "mime_type": "text/html"
            }
        },
        "inherited": False,
        "invalid_field_names": [
            "corpus_id",
            "content_type",
            "last_updated",
            "provenance",
            "path",
            "label",
            "uri"
        ]
    },
    {
        "name": "Speech",
        "plural_name": "Speeches",
        "fields": [
            {
                "name": "act",
                "label": "Act",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "keyword",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "scene",
                "label": "Scene",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "keyword",
                "choices": [],
                "cross_reference_type": "",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "lines",
                "label": "Lines",
                "indexed": False,
                "unique": False,
                "multiple": True,
                "in_lists": True,
                "type": "cross_reference",
                "choices": [],
                "cross_reference_type": "PlayLine",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "speaking",
                "label": "Characters Speaking",
                "indexed": False,
                "unique": False,
                "multiple": True,
                "in_lists": True,
                "type": "cross_reference",
                "choices": [],
                "cross_reference_type": "Character",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "text",
                "label": "Text",
                "indexed": False,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "html",
                "choices": [],
                "cross_reference_type": "",
                "synonym_file": "early_modern",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            },
            {
                "name": "play",
                "label": "Play",
                "indexed": True,
                "unique": False,
                "multiple": False,
                "in_lists": True,
                "type": "cross_reference",
                "choices": [],
                "cross_reference_type": "Play",
                "indexed_with": [],
                "unique_with": [],
                "stats": {},
                "inherited": False
            }
        ],
        "show_in_nav": True,
        "proxy_field": "",
        "templates": {
            "Label": {
                "template": "{{ Speech.act }}.{{ Speech.scene }}.{{ Speech.line_number }} ({% for speaker in Speech.speaking %}{% if not forloop.first %}, {% endif %}{{ speaker.name }}{% endfor %})",
                "mime_type": "text/html"
            }
        },
        "inherited": False,
        "invalid_field_names": [
            "corpus_id",
            "content_type",
            "last_updated",
            "provenance",
            "path",
            "label",
            "uri"
        ]
    }
]