import random
import os
import base64
import hashlib
from io import BytesIO
from PIL import Image, ImageDraw, ImageFont

FONT = os.path.dirname(os.path.abspath(__file__)) + '/last_draft.ttf'
WORDS = ["misery", "rushie", "straunge", "intelligent", "begotten", "multiply", "females", "coniunct", "offen",
         "quarel", "luckie", "extraordinarie", "grewe", "carryed", "approued", "graue", "auoide", "sorrow", "bleeding",
         "disloyall", "wotting", "kingdome", "foredoone", "squiny", "child", "murrion", "diuine", "conductor",
         "yongest", "dearer", "offending", "muffle", "ceases", "corners", "drewe", "controwle", "spake", "seize",
         "gifts", "eminence", "crueltie", "penury", "lowest", "europe", "lying", "cupation", "huntsmen", "fierce",
         "priuily", "batty", "hostesse", "stars", "resigne", "wonders", "stomacke", "vneasie", "rattling", "closet",
         "rotted", "matters", "proclayme", "heauinesse", "leaning", "allowance", "ribbons", "touch", "orelooke",
         "benefit", "parties", "bedabbled", "addes", "yeeldes", "lillies", "sadde", "teeth", "mainly", "trick",
         "butterflies", "griefes", "hathorne", "comedy", "drops", "wayting", "former", "despised", "hands", "expound",
         "mildewes", "hyppolita", "wholsome", "dishonour", "ocasions", "luxurie", "tabor", "threats", "immediatly",
         "plain", "adieu", "discernes", "madame", "mustie", "loadstarres", "smels", "speculations", "chaunts", "rings",
         "yssue", "opulent", "fortunately", "nuing", "riddles", "glittering", "trade", "hearing", "mouse", "dutch",
         "browed", "aboord", "prodigall", "musicall", "discernings", "cawing", "stories", "drown",
         "drinke", "pertinent", "leuell", "comming", "punisht", "mender", "frenzy", "maliciously", "colour", "surmizes",
         "stemme", "morning", "insufficiency", "marke", "dumbnes", "ballet", "bidst", "maiesty", "sphere", "charme",
         "pocket", "holyer", "leachers", "sterne", "vnfolds", "forges", "pursue", "discharged", "hearts", "feele",
         "torment", "imitate", "interpretation", "sinesse", "louder", "gouerne", "sowle", "mettall", "visitors",
         "disclaimes", "apart", "slipshod", "vouchsafe", "feard", "remoue", "moystened", "prepare",
         "weapons", "filthy", "exact", "flood", "shrike", "mamillius", "droop", "votresse", "right", "numbred",
         "crauing", "lawyers", "theseus", "baite", "richer", "controule", "thracian", "hempen", "customers", "beard",
         "fairest", "fixed", "ioues", "worth", "ounce", "impaire", "thinke", "queene", "knots", "stood", "missingly",
         "measur", "girdle", "aloofe", "stirre", "manet", "ordinance", "maugure", "slide", "purchase", "ouerwatch",
         "leuiathan", "prouoking", "harder", "raigns", "wormes", "sheets", "pompe", "looks", "thebes", "melancholy",
         "solely", "maidens", "neighbors", "impeach", "couldst", "yokefellow", "fierie", "betrayed", "whyning",
         "creating", "disquietly", "grant", "incorporate", "succeed", "mayest", "garments", "aduice", "lyers", "feasts",
         "formerly", "height", "taylors", "defects", "fogge", "stocken", "mischeefe", "fiend", "potion", "weathers",
         "fiftie", "trickes", "offences", "misprision", "tirra", "appeared", "slipperie", "rebellion", "villain",
         "affaire", "qualitie", "trifle", "rimes", "three", "escape", "wordes", "names", "banishment", "william",
         "cornwal", "prima", "attendant", "lamented", "reigning", "deserues", "spider", "prepost", "tells", "temples",
         "return", "lownes", "eating", "bigger", "beguil", "scarr", "dumbnesse", "cytherea", "spheare", "ianuary",
         "demaunding", "rurall", "sights", "reconciles", "impose", "lands", "pearce", "meanest", "askes", "bootes",
         "waterpots", "drinkes", "houre", "proue", "fastened", "gentlemen", "muses", "faints", "yoake", "fretfull",
         "lubbers", "fighting", "shooes", "coldly", "cordiall", "discretion", "protect", "physicks", "tyranous",
         "ignobly", "forgot", "edgar", "pinching", "vncertaine", "bankrout", "curtesies", "moonelight", "briefly",
         "howers", "fasting", "eagles", "drowne", "france", "vengeance", "worship", "first", "corne", "despight",
         "extended", "dogge", "battels", "windes", "quicken", "didst", "guiding", "thrifts", "passage", "flight",
         "owest", "caled", "swiftly", "minute", "possest", "obscenely", "amisse", "coate", "farwell",
         "vnseene", "dissipation", "hermione", "souerainty", "womens", "serued", "together", "count", "aduenture",
         "churle", "belou", "returnes", "reuenue", "heede", "praises", "dolour", "dower", "hippolita", "cornewal",
         "officer", "lappe", "vnsphere", "parents", "lamely", "terribly", "pietie", "scandall", "hippes",
         "pickt", "sounds", "merlin", "rosemary", "glassegazing", "returned", "skies", "boaring", "contract", "vnfeed",
         "sauage", "incestious", "coats", "destiny", "doubler", "spyes", "burning", "lation", "chose", "apollo",
         "bower", "stupified", "faithfull", "denying", "estate", "vilaine", "aduersarie", "publikely", "pushes",
         "themselues", "italian", "obseruance", "doing", "slayer", "spaniel", "mispris", "reuerent", "thereat",
         "forkes", "satisfaction", "marble", "potentiall", "disasters", "waters", "frownes", "restore", "crosse",
         "respectively", "stranger", "cupid", "cracke", "posterity", "contracted", "nightrule", "thereto", "wildly",
         "begins", "churgion", "spice", "gloues", "showes", "solemnitie", "freely", "strooke", "consider", "worthier",
         "ampler", "howsoeuer", "excellent", "increase", "malicious", "ruine", "waigh", "sheerers", "greets", "pearles",
         "generation", "bitter", "fitter", "disfigure", "reciprocall", "crulentious", "spoke", "cornwals", "paying",
         "admiring", "clamour", "lowers", "sauour", "nobles", "austeritie", "muzzel", "recoyle", "adulterers",
         "proceedings", "outwall", "fleach", "oswald", "dragons", "acquaint", "valleyes", "seruer", "possesse",
         "munkies", "yeare", "respectes", "throstle", "venomously", "these", "lyuer", "serues", "mayst", "spectacles",
         "doest", "deuise", "deucalion", "capitall", "mysterie", "pertaine", "knocke", "riotous", "gazes", "secretly",
         "gazing", "nitie", "apace", "costs", "helen", "gilded", "double", "vncouple", "widowe", "blessednesse",
         "images", "asleepe", "snatch", "scalpe", "onely", "lastly", "bringing", "thereabouts", "sequent", "smilets",
         "offend", "legges", "subdue", "start", "blest", "sufficiency", "looker", "willingly", "soueraignely",
         "pallaces", "starke", "worthiest", "president", "dined", "flowen", "character", "abhorred", "familiarity",
         "filiall", "operation", "strain", "ethyopians", "credulitie", "prone", "preserue", "gentry", "actus",
         "raignes", "prosecute", "ponder", "blade", "gonor", "adulterie", "loffe", "others", "litter", "vnnumbred",
         "elues", "seemes", "squires", "rocks", "equall", "conclusion", "remote", "bowling", "close", "designe",
         "check", "penitent", "curphew", "demand", "began", "packings", "allow", "tender", "lynes", "borest", "beaten",
         "elements", "committing", "discharg", "desirest", "bragart", "acquain", "extend", "veines",
         "appertaines", "serious", "feeding", "meades", "brothell", "vvherefore", "vildely", "vaunt", "torments",
         "edmond", "browch", "nailes", "amazement", "going", "featly", "tucket", "single", "royalties", "vixen",
         "skill", "clearer", "letcher", "iudgement", "medicin", "thread", "ouerbeare", "packt", "witch", "hilloa",
         "headed", "robbed", "dolphins", "looke", "displeasure", "packe", "treasury", "abusd", "authorities", "tempt",
         "shrewdly", "tytania", "fartheewell", "sacred", "requisite", "delphos", "scornes", "sudden", "gallowes",
         "embassies", "neede", "sessions", "presented", "triumphant", "leaues", "striues", "streak", "cheate",
         "trespas", "drowned", "honisuckle", "readie", "suspition", "flying", "appear", "vncle", "quintus", "earthlyer",
         "prophesie", "corrupted", "guide", "further", "furlongs", "obtayn", "vrges", "tartar", "coknay", "doting",
         "lasses", "weeds", "pieces", "degenerate", "painter", "flatteries", "ioyes", "traytor", "repeals",
         "displeasures", "corruption", "bowstrings", "counterfait", "vnnecessarie", "beginning", "foote", "dispatch",
         "conceaue", "sirah", "brisky", "peere", "lackes", "scriech", "cypresse", "fenced", "loopt",
         "gainst", "mazes", "parting", "phantasies", "aurynted", "infirmitie", "wodden",
         "mildie", "brats", "threede", "attentiuenesse", "bastards", "stocke", "strange", "inclin",
         "modestie", "behinde", "villanie", "pitties", "noyse", "sirrah", "iuice", "traunst", "speach", "peaces",
         "sheete", "turnd", "plesure", "taine", "pitteous", "dread", "wretches", "winter", "offic", "douer", "possible",
         "graine", "lowly", "hainous", "hazard", "cunning", "naturall", "codpis", "enemies", "vnbuckle", "sanctity",
         "lacke", "manner", "smell", "beloued", "heresie", "prouided", "beauty", "titania", "shore", "stubborne",
         "swaggar", "harke", "enterlude", "kissing", "cracking", "infect", "become", "twenty", "curtains", "ciuill",
         "dedication", "alacke", "tenant", "whippe", "shirts", "kneeling", "iangling", "euermore", "paine", "contemnd",
         "creete", "ified", "henchman", "iuuenall", "accurst", "newly", "whither", "bargaine", "april", "concluded",
         "murder", "daugh", "warmer", "actors", "lodes", "sicillia", "stretch", "tremor", "deliuer", "kinds", "vnfed",
         "merits", "trespasse", "breaking", "vigilence", "fairyes", "dians", "forefend", "conuey",
         "deeds", "midnight", "besort", "month", "motiue", "plainly", "hagge", "quaile", "imparts", "affront", "coarse",
         "operatiue", "gunnes", "windowed", "vnconsidered", "naming", "distemper", "sheald", "creatures", "suites",
         "extremitie", "losses", "gotish", "wheresoere", "trild", "although", "stobing", "scratch", "concerne",
         "wanderer", "yeere", "sinewes", "landed", "purse", "embracing", "hermia", "fetch", "ratsbane", "approach",
         "affear", "humane", "expresse", "launces", "beleeft", "noystles", "sauors", "summoners", "daunce",
         "exhibition", "goodfellow", "cherish", "autumne", "enammeld", "affect", "admirable", "hearke", "argue",
         "detaine", "lysander", "allows", "trusted", "muske", "blessing", "stomack", "heard", "centinell", "fecks",
         "plainer", "raritie", "lamenting", "madmen", "iudicious", "mustard", "camillo", "ditch", "exercise", "bugge",
         "nointed", "sealing", "disdain", "tough", "pined", "opportune", "vndergo", "boone", "burgundie", "chaplet",
         "wodde", "slaughters", "wholesome", "hurtlesse", "sillable", "therfore", "dangerous", "husbands", "dotard",
         "fraunce", "cadmus", "tyring", "chastitie", "impression", "clymate", "scape", "earthly", "fruitlesse",
         "retreat", "least", "annoint", "scandalous", "spiced", "wantons", "strangenes", "hanged", "grieue", "reysons",
         "affections", "creast", "mones", "cambrickes", "footing", "import", "schooling", "scratcht", "disorders",
         "topples", "bones", "hande", "knacke", "brittish", "vttred", "simplenesse", "medcine", "presenteth", "scene",
         "pastime", "drencht", "albion", "stirres", "north", "thysby", "dowre", "venter", "conceals", "tremble",
         "pride", "trumpets", "cocke", "taylor", "squar", "rebuke", "instrument", "reueling", "horrible", "worshippes",
         "particulars", "combs", "other", "alone", "behold", "thourt", "surpassing", "hither", "stench", "rheumes",
         "neeze", "vnhappie", "amiable", "philostrate", "bases", "shewe", "neutrall", "bringer", "finder", "impediment",
         "heers", "shaping", "aboue", "blossome", "mistery", "soldiers", "blesse", "reuenge", "garter", "apple",
         "swownded", "graues", "oreturnd", "mooue", "kisses", "infection", "noonetide", "twelue", "curre", "infant",
         "darkenesse", "immediately", "brick", "coactiue", "imagine", "spaniell", "sentences", "faintly", "vexation",
         "accept", "notable", "honey", "slanders", "noted", "fower", "demetrius", "hauthorne", "curtesie", "surpriz",
         "conspir", "kibes", "prerogatiue", "distraction", "lesser", "seeme", "husband", "hereafter", "desperate",
         "emptying", "rabble", "entends", "flyes", "likely", "leaden", "disseuer", "potency", "person", "vnworthie",
         "sleeke", "summon", "prithee", "grossenesse", "shoots", "amend", "fauchon", "garlicke", "confesse", "dragon",
         "knowes", "imbrew", "departed", "preseruer", "depend", "miracle", "already", "wheeles", "thysbyes", "worryes",
         "fearce", "hence", "fleash", "declin", "childehoode", "offer", "manage", "shorne", "ducke", "striue", "liquor",
         "periur", "flights", "tartars", "coming", "semblance", "loathing", "ielly", "euident", "fairst", "iewell",
         "bewray", "weauer", "gather", "lisander", "plant", "sprights", "cursse", "crowes", "blanket", "thether",
         "enioyn", "force", "confirmation", "plucking", "moytie", "beetles", "ioycing", "disliken", "stucke", "speech",
         "neigh", "beams", "vnpath", "fruit", "lipsburie", "pearle", "sicilia", "courted", "traytors", "apparrell",
         "thers", "couert", "smooth", "spleene", "wombes", "varlet", "pated", "saide", "remained", "charmed", "bounty",
         "tinkers", "tragedy", "vnrold", "cozeners", "description", "pouertie", "holly", "peepe", "businesses", "abhor",
         "sense", "rightly", "tamenes", "hardned", "sweetest", "reuerence", "frend", "caualery",
         "lyons", "infancie", "dryed", "mantle", "runnes", "loynes", "capable", "loathed",
         "vtterance", "iulio", "mulberry", "howre", "crimes", "hideous", "flatter", "edmund", "marry", "henceforth",
         "creame", "bosome", "beholde", "nuptial", "stript", "oberon", "warnd", "flatterer", "rigour", "mutuall",
         "trippe", "gests", "lusty", "vvoolfe", "hated", "monthly", "relieued", "chamber", "could", "ballad", "happy",
         "vnpublisht", "spurne", "forke", "against", "fooleries", "compact", "mentioned", "reflect", "dolphin",
         "transforme", "thistle", "earnestly", "albany", "arint", "dayly", "bragging", "gratitude", "answers", "weake",
         "prayer", "offered", "shouldst", "weeke", "prisoner", "businesse", "groome", "bedlom", "vngentle",
         "complement", "commanded", "worst", "delaid", "mistris", "witnesseth", "rayment", "picture", "plentifully",
         "little", "minding", "wishes", "shake", "impatience", "abridgement", "thriuing", "veryer",
         "mingled", "answered", "espies", "greater", "perfor", "those", "coren", "othersome", "robbe", "pidenesse",
         "videlicet", "dotage", "apricocks", "froth", "pitifull", "vnbonneted", "tonguelesse", "alwaies", "wrathfull",
         "casualties", "cares", "barke", "plainest", "bleedst", "flesh", "vndertake", "neatherstockes", "whereto",
         "hedge", "stoole", "plead", "layes", "sweepe", "neere", "perfit", "profound", "betimes", "rooted", "crewell",
         "forrest", "dismissing", "vndone", "gentles", "appearing", "shortens", "contents", "fairely",
         "risen", "trusts", "indur", "steale", "knighthood", "prepared", "wrinckled", "opinion", "preparation", "bites",
         "nosegaies", "cease", "generally", "hatred", "counsailes", "sticall", "friend", "notably", "silkes",
         "deuoutly", "kindes", "desir", "played", "pedlers", "treasurie", "steepe", "deflour", "forst", "detestable",
         "collect", "patent", "behoue", "persons", "beakes", "oppression", "weepes", "imprison", "tarie", "curious",
         "diuelish", "lyars", "nestie", "grafted", "created", "neafe", "throngs", "seruingman",
         "poynt", "torture", "reiterate", "querne", "blanch", "companions", "assembly", "phantasie", "beached",
         "forbid", "medling", "greatnesse", "flitkering", "hurrying", "cruelty", "court", "tricke",
         "butler", "wiseman", "meere", "proude", "continents", "vnknowne", "negligence", "thisbyes", "pierce",
         "dignities", "shape", "particuler", "purchas", "vnsetled", "grumble", "rights", "nunne",
         "christall", "depriue", "relish", "since", "expos", "brazen", "lillie", "consort", "sawcely", "carried",
         "validity", "stick", "obscured", "playes", "accord", "yeelded", "bringes",
         "praise", "figure", "horred", "geese", "staire", "charitable", "spell", "madde", "charge", "nymphes", "hayrie",
         "leagues", "talkt", "descend", "opportunitie", "addrest", "defend", "troope", "quoifes", "cheerd", "purposed",
         "sentence", "iewce", "obseruants", "labours", "prepar", "shamefull", "deepest", "heauens", "professes",
         "carthage", "vaward", "smile", "blowne", "musique", "perpetuitie", "dewlop", "instruments", "purposes",
         "trusty", "shrewde", "contriu", "vnseale", "perties", "flame", "successor", "abhominable", "houselesse",
         "iermaine", "surfeit", "learnedly", "vncleane", "euasion", "sicknesse", "altitude", "swimme", "arise",
         "mutinies", "verses", "tours", "preuaile", "pittifull", "pursuit", "retinue", "tertia", "chaffe", "chast",
         "according", "getting", "phillida", "waile", "church", "twere", "sauours", "boasted", "blossomes", "forraine",
         "spright", "attyr", "seething", "veluet", "voyces", "enthrall", "gorge", "trafficke", "neuer", "highnes",
         "tawnie", "refresh", "partner", "slacke", "recorder", "ornaments", "heaping", "players", "bagge", "lending",
         "handsomely", "priuately", "entertaine", "raggs", "voucht", "vices", "commends", "manners", "hower", "croke",
         "curds", "shuts", "disturbe", "dogges", "sapient", "antigonus", "embarked", "scythyan", "learne", "knife",
         "cariere", "fought", "returnd", "rauished", "handed", "signe", "pight", "trotting", "bounds", "studied",
         "perchaunce", "lushious", "grimly", "bless", "example", "safty", "informd", "darke", "frustrate", "dysses",
         "grauer", "vnvenerable", "stincke", "pucke", "clipping", "misconstruction", "disordered", "oxlips",
         "heardsman", "iealousie", "sommons", "wedding", "front", "abated", "brothers", "reproueable", "altar", "brand",
         "morne", "autolicus", "twice", "recounting", "which", "comodities", "troupes", "puppets", "faint", "murthered",
         "intelligencing", "dyest", "reeking", "enormious", "nothings", "vpward", "greefes", "scarre", "warriour",
         "harmefull", "cross", "lethargie", "defil", "consum", "nodding", "tutch", "pursse", "performe", "lawnes",
         "beholding", "priuate", "forces", "vncurrant", "oathes", "mouthes", "doune", "remedies", "wickednesse",
         "catastrophe", "addres", "instruct", "please", "callat", "pursues", "effects", "halters", "exultation",
         "sodainly", "humanly", "smutch", "scorning", "thoud", "better", "smallest", "humble", "thighes", "vnparallell",
         "named", "vnclasp", "celestiall", "embrac", "subscrib", "desart", "murderous", "picking", "foyns", "fixes",
         "affrighted", "smoothe", "actions", "guard", "origin", "punish", "buried", "virgin", "defences", "decline",
         "vnhardened", "demet", "bracelet", "moone", "keepe", "trinkets", "chaung", "wofull", "torturing", "patterne",
         "commaund", "corrupter", "goale", "young", "tearmes", "griefe", "errand", "dible", "spite", "starry", "russia",
         "headlong", "gayes", "musick", "entend", "fulfill", "instructs", "catch", "slaughter", "visit", "arguments",
         "madnes", "reuokt", "maintaine", "hairy", "disobedience", "lasse", "destroy", "yeelds", "howle", "funerals",
         "issues", "splitt", "periode", "instance", "egges", "expose", "execute", "perswaded", "fruitelesse", "blush",
         "curse", "riualles", "choose", "receiue", "miscary", "forty", "sainted", "theefe", "forgeries", "sympathy",
         "fanta", "portable", "changeable", "chaffes", "roughcast", "vndertaking", "entred", "giuen", "dishonord",
         "respecting", "prooues", "differences", "iustify", "twentie", "wildely", "papers", "hermias", "barren",
         "auditor", "merrily", "enrich", "piramus", "shafalus", "honybagge", "beware", "substance", "tenor", "purge",
         "madly", "strong", "physicke", "calender", "wrote", "trace", "robin", "crosses", "state", "consent",
         "preferre", "fated", "pyping", "trifles", "keene", "whose", "goodliest", "lysan", "fortun", "reuenewe",
         "mooneshines", "chance", "tenth", "scales", "heycfer", "between", "sriberdegibit", "baudes", "auncient",
         "wagtayle", "illusion", "slenderly", "daughters", "amitie", "tendernesse", "couple", "waking", "instantly",
         "surrender", "sworne", "shames", "accused", "makers", "professe", "ignorance", "bryer", "iesters", "tinker",
         "acquaintance", "sisters", "forward", "sions", "meane", "inough", "neerest", "pilot", "historica", "deerest",
         "progeny", "yield", "delight", "terrors", "autol", "rumor", "whereupon", "descent", "bursts", "messenger",
         "beshrew", "insues", "tyres", "brach", "guestwise", "noses", "trayterous", "prosperous", "stiffe",
         "homespunnes", "handfull", "aduis", "souldier", "bowes", "moons", "truely", "candle", "actor", "paragon",
         "meanes", "continue", "sleep", "regan", "footed", "behooues", "smiles", "maidenly", "sommers", "sustayn",
         "detest", "despise", "pearing", "killing", "commoditie", "bragd", "fresh", "daunces", "bastardie", "soldier",
         "richest", "alteration", "horrid", "perdita", "heartily", "prewyns", "aloud", "counted", "valentine", "chinne",
         "finde", "hatefull", "hourely", "perill", "moonshine", "huswife", "despis", "cogitation", "giues", "excesse",
         "affoord", "sicily", "louest", "arrowe", "tailes", "transparent", "customary", "sweetnes", "carcasse",
         "flowes", "doores", "loued", "leekes", "ingredient", "virginitie", "exposition", "holdst", "stole", "foole",
         "rogero", "mockers", "almost", "pitious", "raging", "endeuours", "seeds", "gambols", "neate", "receiuing",
         "highway", "temple", "walks", "flatterie", "remember", "proofes", "peering", "backe", "ordinarie", "threatned",
         "melody", "roare", "casement", "agent", "instructions", "smiling", "deriuatiue", "outfrowne", "goose",
         "puissant", "tunable", "boorde", "confusion", "bearest", "tutors", "foredoome", "exile",
         "sarum", "fancy", "ercles", "moment", "droppes", "curld", "planitary", "wherein", "philost", "filly",
         "bounsing", "venturous", "bearer", "thunder", "sprightly", "vnthought", "cordelia", "enthralled",
         "false", "clothiers", "tumbe", "sulpherous", "audacious", "hearte", "light", "debate", "squirils", "rayld",
         "pitied", "moitie", "cautions", "escapt", "ducking", "apparant", "vndream", "chinke", "deawlapt", "parts",
         "valor", "forbidde", "preferment", "dance", "triple", "desire", "kinder", "shrug", "scornefull", "lurke",
         "sinister", "remedie", "nobly", "flattering", "trauaild", "tougher", "flawd", "heauenly", "cypher", "yeoman",
         "wingd", "accident", "glide", "pease", "shapes", "showen", "rustiques", "foolish", "vnnaturalnesse", "bondage",
         "important", "maidenlest", "smocke", "dullard", "fatall", "harpe", "fordid", "wearie", "eternall", "growne",
         "yeelders", "lawed", "inckles", "cleans", "sweet", "schoolemasters", "milliner", "endured", "beginne",
         "officious", "extreames", "throw", "building", "roring", "sorrowes", "heigh", "harte", "censure", "flocke",
         "pallace", "sight", "gossipt", "impertinencie", "makeing", "scorne", "becomes", "behalfes", "opposite",
         "keeping", "mobing", "mungril", "coniur", "shaft", "detested", "buttered", "hound", "handy", "charity",
         "weapon", "mingle", "milke", "precedent", "blacke", "musters", "penny", "falles", "plaies", "dispose",
         "spottes", "aduocate", "dignity", "parted", "abatement", "speed", "frantick", "mortified", "bigge",
         "incertainties", "highnesse", "flakes", "enridged", "borne", "vnkinde", "promotion", "paulina", "vnluckily",
         "coole", "hotly", "forcefull", "doome", "childish", "infusion", "female", "chaine", "imposition",
         "cheeke", "carbuncle", "reuenges", "imprinted", "search", "walke", "withhoulds", "tayles", "passed",
         "chambermaids", "biding", "gambole", "cabine", "pesant", "replenish", "tearing", "hoping", "heauie", "water",
         "entreat", "ference", "vnsightly", "prancks", "carie", "gentlewoman", "armed", "entwist", "vnstain", "enmitie",
         "stiberdigebit", "nakednes", "nurses", "compulsion", "westerne", "desperatly", "lawes", "reneag", "blocke",
         "louer", "sauory", "coward", "coyle", "caddysses", "streames", "successefull", "blusht", "fancie", "singular",
         "haunts", "prithe", "battel", "sincere", "starres", "straw", "spiders", "vndiscouer", "lockt", "longer",
         "medicine", "extreamely", "domestique", "concealed", "raigne", "vault", "forsooke", "pressed", "dislecate",
         "parcels", "francis", "radience", "condemnd", "secunda", "proceeding", "scarce", "square", "interchained",
         "browne", "thrumme", "turns", "marshall", "loyall", "negligent", "secrecie", "answer", "accuse", "cleare",
         "somthing", "transformed", "beneath", "sawcily", "seruice", "barme", "fynch", "knight", "pittie", "seales",
         "silently", "watch", "stand", "mirth", "steps", "beginnes", "sliuer", "gentler", "vnremoueable", "turfe",
         "habits", "athenian", "flowers", "strikes", "because", "hangman", "memories", "ghesse", "raile", "though",
         "exercises", "wittiest", "blench", "torne", "ception", "simular", "vnburthen", "honors", "silke", "committed",
         "mouing", "vsurer", "vpright", "tyranny", "ninus", "curio", "testimonie", "tript", "steere", "cornwell",
         "destroyed", "easie", "glars", "mearemaide", "morris", "threatning", "cooles", "raggednes", "suspect",
         "chaire", "zeale", "mistres", "offendors", "starueling", "think", "seauen", "turke", "summers",
         "draws", "schoolemaster", "handle", "nough", "despisd", "nayle", "hight", "theres", "small", "moods",
         "referre", "dissolued", "stication", "shrill", "pestilent", "ouertake", "hostesseship", "flaunts", "daube",
         "wooden", "apish", "vnmercifull", "written", "principall", "paines", "widdow", "protection",
         "suitor", "pleading", "impaired", "proiect", "reputed", "fasten", "clothes", "shoare", "beggers",
         "premeditated", "diest", "snowte", "breeches", "appetite", "starre", "respect", "imaginations",
         "embrace", "blemish", "deawe", "perigenia", "maruailes", "prouoke", "interest", "towne", "reprouing",
         "easiest", "leads", "vaine", "mature", "brasse", "cursed", "paire", "alwayes", "saltiers", "sences",
         "seperati", "almanack", "cheere", "bayliffe", "pantingly", "swift", "stroke", "headelesse", "titles", "stayes",
         "dutious", "beside", "hollownesse", "visited", "frontlet", "yeares", "ribbon", "sumter", "taste", "singes",
         "pendulous", "might", "deare", "dunghill", "tifull", "disease", "winged", "pinch", "iustified", "satyres",
         "westward", "prouerb", "thorns", "neerer", "monarch", "prophets", "touches", "mungrel", "vttering", "rellish",
         "incident", "tread", "vouchsaf", "swear", "dearest", "placket", "tunes", "contaned", "whether", "carnations",
         "sprigs", "malice", "vnquietly", "incidencie", "soaking", "reseru", "bottoms", "verily",
         "vniust", "shepherds", "offices", "spurre", "findings", "parlous", "abused", "theile", "pinfold", "brands",
         "nobleman", "recreant", "notice", "kingdomes", "limit", "cheekes", "fountaine", "counterfaiting", "sleeues",
         "follies", "sluyc", "seuerall", "penning", "procrus", "snout", "wouldst", "combat", "prithy", "proclaime",
         "calfe", "harted", "questions", "carpe", "denie", "gesture", "heyres", "stickes", "railes", "curtaine",
         "wafting", "gardens", "berlakin", "number", "flechuent", "chizzell", "snowe", "ioyner", "roundell", "pregnant",
         "thereof", "eeles", "spreds", "spoyle", "cowardize", "haire", "mothers", "captaine", "reuoke", "alliance",
         "losse", "frollick", "repent", "instant", "striuing", "hardly", "emperor", "hotest", "accusation", "values",
         "expense", "soiorne", "conioynd", "palpable", "innocent", "worme", "falcon", "woolfe", "counterfeiting",
         "beardes", "boare", "nought", "weale", "broken", "iustly", "boulted", "shiuer", "mercifull", "quire",
         "padling", "lanes", "beseech", "scard", "limber", "honour", "enioy", "cordes", "midst", "nightly", "ieast",
         "latches", "equity", "strayn", "grime", "mistresse", "prize", "diuest", "stolne", "spoak", "visiting",
         "distribution", "applied", "absent", "riuall", "sands", "wonne", "bully", "barky", "frisk", "charities",
         "sings", "laught", "balmed", "saffron", "promist", "tailour", "loyaltie", "findes", "alike", "outsleepe",
         "vtter", "brawles", "delay", "pinion", "shaddow", "weares", "afresh", "finicall",
         "superstitiously", "simplicitie", "dearth", "tempest", "truncke", "nellthu", "altogether", "slippe", "bayed",
         "bawdy", "vnder", "bugle", "stone", "letters", "miseries", "pigmies", "without", "cowslippe", "meate",
         "rounding", "damned", "turtle", "puppet", "falne", "snayle", "auspicious", "gloue", "barre", "vnion",
         "coxcombs", "wander", "acorne", "perdy", "serpent", "leauing", "derision", "breefnes", "streake", "reuennew",
         "hitherward", "obidicut", "commend", "couers", "lullabie", "seems", "acceptance", "array",
         "liues", "limander", "contempt", "suffered", "forsaken", "whisperd", "laying", "protest", "boastes", "quest",
         "violence", "acknowlegd", "vnprouided", "absolute", "amber", "cryes", "thisbies", "cowardise", "conniue",
         "ouerture", "setled", "decay", "machination", "perswades", "houres", "steep", "vilains", "triumph", "learnt",
         "youth", "thunders", "reads", "lilly", "floods", "aduise", "meates", "beggerly", "flowre", "tride", "commune",
         "detaines", "presently", "witnesse", "taken", "posted", "seare", "tales", "cleauing", "peeter", "steppe",
         "depart", "duties", "prank", "gasted", "princesse", "adders", "preach", "guilt", "thick", "sallets", "merited",
         "dissention", "feast", "trifell", "reasons", "struck", "presse", "dispute", "stumble", "commands", "poaking",
         "allay", "worthied", "constancy", "giltles", "whereon", "benefits", "princes", "villageree", "sacrifice",
         "ragan", "cracks", "conflict", "proclamation", "eares", "tongues", "remouednesse", "pleasure", "hayle",
         "hastning", "millo", "enough", "polititian", "laughter", "taske", "othes", "stumbled", "horned", "ingrafted",
         "hastily", "vnkindnes", "easier", "rarer", "cranie", "money", "neglect", "vnable", "acknowledge", "sheetes",
         "habitation", "fellowship", "impawnd", "sicke", "quench", "blocks", "warmth", "visitation", "margerie",
         "daphne", "traitour", "iumpes", "thinking", "perpendicularly", "royally", "egeus", "statures", "counsaile",
         "traitor", "experienc", "resume", "plunge", "iniury", "currence", "solemnely", "almes", "bottom", "roares",
         "earle", "bench", "bespoke", "stile", "dirty", "deliuerie", "parchment", "finer", "orecharged",
         "vnderstanding", "expect", "terme", "appointed", "cries", "perceiued", "septima", "haunted", "dismist",
         "patient", "entit", "tenderly", "benizon", "warme", "topple", "particular", "boyling", "reremise", "spied",
         "fauor", "braunch", "approch", "fools", "halfe", "death", "reuenew", "cried", "mourne", "theirs", "question",
         "albaines", "wakest", "angry", "hanging", "meade", "wisdome", "twise", "minikin", "foulnes", "ramus", "curst",
         "celebrated", "bastard", "seede", "becomming", "witchcraft", "touching", "predominance", "thessaly", "bawcock",
         "vnwillingly", "torches", "seruile", "compast", "bloody", "vneauen", "sweld", "sides", "asunder", "rogish",
         "fishe", "ingenious", "vnderta", "feare", "alarum", "approbation", "follower", "owner", "shearing", "window",
         "pretence", "waxen", "imperiall", "scalding", "obedience", "pomander", "quencht", "world", "wills", "vnlou",
         "murdred", "suddaine", "archery", "engine", "ransackt", "taking", "gnawne", "louing", "embraces", "mazed",
         "pecke", "commonly", "thrush", "flatnesse", "gloriously", "ausrent", "prankes", "hounds", "simpring",
         "euening", "clerke", "yellow", "patron", "handles", "wherfore", "changed", "clawes", "citties", "sauor",
         "loosen", "snakes", "quell", "paper", "smild", "wosted", "corkie", "discourse", "wedded", "councell", "abode",
         "belest", "british", "angle", "either", "eleuated", "stampe", "tarry", "eglantine", "wares", "doubt", "oldest",
         "faces", "plenteous", "peece", "horne", "perchance", "purblind", "holding", "cornewals", "cullyonly", "messe",
         "enioyne", "likewise", "transformations", "enforce", "tuelygod", "darknes", "imports", "mouth", "office",
         "writing", "bellow", "releeued", "encourage", "amazedly", "robes", "vnearned", "dreadfull", "hollownes",
         "sexta", "councels", "fayrest", "mindlesse", "gracious", "reason", "element", "chearles", "lords", "messen",
         "friendly", "thickskinne", "scald", "fitting", "distressed", "lightning", "flattered", "brooke", "field",
         "pernitious", "conspiracie", "secrets", "soliciting", "meditation", "ringlets", "properly", "breathles",
         "executing", "rocke", "poorest", "federarie", "abhord", "certainly", "spinners", "thousand", "there",
         "neptune", "witnesses", "odours", "romano", "fainte", "iniunction", "redeeme", "aquavite", "warrant",
         "thisbie", "petition", "blusting", "brother", "restoring", "stirs", "beweepe", "slaine", "create", "cleere",
         "tottered", "settle", "temptations", "freedome", "during", "figges", "imprest", "indow", "marre", "thornes",
         "gonerill", "shewedst", "beadle", "winners", "infinite", "grasing", "comfortles", "historie", "caractar",
         "disquantitie", "insinuate", "corke", "horsemans", "auouches", "pantler", "prettiest", "faine", "aside",
         "enguard", "partake", "royall", "accus", "greeue", "poorlie", "women", "pleated", "spotted", "vsurers",
         "attainde", "basenesse", "madams", "euils", "goodman", "complaint", "forbiddenly", "mayster", "warning",
         "means", "bearing", "enter", "bequeath", "obiect", "aliads", "asham", "thicke", "fallen", "leister", "coast",
         "stage", "toote", "sleepes", "consecrated", "honourable", "aprils", "after", "teach", "himselfe", "vessell",
         "blowes", "hoord", "petitions", "hundred", "personall", "violets", "whoop", "secure", "rysing", "wensday",
         "fully", "braue", "weighed", "gauest", "black", "dispositions", "where", "fates", "crickets", "girle",
         "tipsie", "incertaine", "practiz", "lordshippe", "sunnes", "circumstance", "slumber", "forlorne", "globe",
         "chorus", "shankes", "shorter", "dowerles", "toyled", "stamped", "rowland", "remoued", "descryes", "minces",
         "bossom", "myrth", "golde", "nuptiall", "prince", "digest", "fitly", "cholericke", "informe", "florizell",
         "serpents", "correction", "tyrants", "quesse", "quake", "rages", "eternally", "mariner", "bristled", "shine",
         "towards", "reueald", "hangd", "theft", "beating", "heare", "sonnes", "bussing", "messes", "misse", "suspend",
         "seeke", "dreame", "thred", "forsooth", "faieries", "liking", "pitty", "discom", "fifty", "maids", "creepe",
         "scourge", "carbonado", "counsell", "gouernesse", "crabbed", "chuse", "goddesse", "kickt", "showe",
         "whereof", "storm", "ariadne", "reprehend", "abate", "scornfull", "speakest", "remembers",
         "distracted", "conceiuing", "resolution", "smelt", "ayred", "powther", "gentlenes", "cleerest", "graces",
         "sheepeheards", "stocks", "rotunditie", "poysoner", "monopolie", "minnick", "clouded", "swords", "thousands",
         "easily", "containes", "celebration", "damaske", "discend", "deceiu", "farthest", "bosomes", "cuckolds",
         "thinks", "discord", "deceiuing", "wretchednes", "territory", "antiopa", "poysoned",
         "daugter", "tailer", "bloods", "rheumaticke", "fitnes", "tawny", "richly", "idolatry",
         "purpose", "possesses", "heires", "libia", "honours", "nightingale", "grimme", "offender", "reposure", "haste",
         "receiued", "queenes", "stands", "wisedome", "iniustice", "carries", "vvere", "gular", "traine", "million",
         "sinne", "blamed", "furie", "iustice", "poyson", "scrieching", "vniuersall", "damnable", "iniurie", "crownes",
         "worke", "whistle", "vnbridle", "prime", "perfect", "ladies", "round", "thyne", "feasted", "saucy", "desert",
         "altered", "renowned", "beastly", "rously", "castle", "bending", "weighing", "gladly", "clamarous", "amytie",
         "poore", "rousd", "before", "naughty", "errour", "arriu", "yielding", "occasions", "presageth", "fearefull",
         "breake", "bayts", "heade", "parent", "sheep", "anotomize", "adultresse", "started", "powre", "setling",
         "hinder", "fadom", "intelligence", "plague", "customarie", "sworde", "thinkes", "needs", "heaue", "couslippes",
         "denide", "drawes", "harts", "godson", "chronicled", "sighe", "downe", "whirli", "gathers", "soule", "bumme",
         "spotlesse", "hopes", "signes", "treasons", "sizes", "disparage", "knowst", "prate", "lookt", "wakeing",
         "happier", "publisht", "affayres", "distinguishment", "happely", "snaile", "professors", "calles",
         "boundlesse", "affected", "whiles", "sufferance", "smite", "mudde", "relent", "impudently", "moreouer",
         "beares", "fires", "cases", "iawes", "nuncle", "snurff", "snyted", "misselead", "vnheedy", "indiscretion",
         "being", "ayery", "hours", "battaile", "haires", "thisne", "scepters", "pawne", "citie", "flout", "charms",
         "laide", "mutations", "lordship", "amorous", "bastardy", "kindnes", "companion", "cousned",
         "beddes", "professed", "mighty", "curtsie", "cutter", "match", "conduit", "rough", "preseru", "sleepie",
         "short", "insulted", "charitie", "posts", "wandring", "spheares", "eight", "radiant", "confirme", "mortalitie",
         "standes", "harbinger", "vicious", "minde", "bandy", "causes", "looses", "clipt", "broacht", "speak", "iuyce",
         "lance", "contraries", "hedgehogges", "bountie", "enchantment", "fadome", "release", "sugar", "chatter",
         "ransom", "shepheards", "tauerne", "thrower", "treacherie", "monstrous", "rayse", "shone", "habited",
         "vnfilliall", "eithers", "deadly", "fathered", "liuery", "vnhappily", "performance", "bordered", "integritie",
         "looking", "suckt", "waywardnes", "withdraw", "assalted", "diligence", "entreaties", "oyles", "saying",
         "preuail", "people", "appollo", "display", "punnishes", "twoes", "conduct", "blame", "ceaze", "careful",
         "fauours", "snatching", "sounded", "heeles", "curses", "dominions", "wisely", "necessitie", "shadow",
         "hemlocke", "sheeres", "waste", "dishonestie", "apprehend", "weigh", "rayne", "murtherer", "shiuerd", "table",
         "length", "penitence", "bloode", "pretious", "complexion", "needful", "needes", "through", "stale", "daughter",
         "baggs", "parke", "luster", "conceyue", "boord", "chiding", "craft", "masts", "cride", "gueld", "talkest",
         "belike", "dotes", "waggon", "hateth", "shewed", "rascall", "warre", "slipt", "vncaught", "sicknes", "dowager",
         "forrests", "knowledge", "speakes", "whisp", "muddy", "impetuous", "meetes", "pheazant", "attornyed", "peeces",
         "priests", "wasted", "abiure", "wound", "extort", "visible", "returne", "vngratefull", "guild", "neyghing",
         "playing", "filcht", "fayre", "therein", "defuse", "darkenes", "schoole", "greefe", "vertues", "nediction",
         "shepheard", "cowslippes", "seruation", "whores", "dementions", "guilded", "below", "perfectly", "action",
         "heereafter", "feature", "soiourne", "yonger", "asses", "winds", "rarest", "bashfulnesse", "noblenesse",
         "shielde", "songs", "meare", "sucking", "spirit", "waded", "hecates", "lightnings", "servant", "liueries",
         "cherry", "lament", "banners", "whitenesse", "eater", "prophecie", "codpeece", "wilfull", "subscription",
         "accent", "disclaime", "tongs", "drunkards", "wolues", "censured", "drooping", "crowe", "added", "aduanct",
         "dutie", "dwels", "spurres", "tombe", "raise", "fruitfully", "indeede", "player",
         "ingratitude", "keyes", "euidences", "seueralls", "hates", "disposition", "wonted", "baitings", "known",
         "preferd", "reputation", "dowreles", "imagination", "finds", "dungell", "broome", "snugge", "battell",
         "teares", "stuff", "reuerse", "tigers", "nether", "pelting", "discouery", "obedient", "runaway", "fooles",
         "abroad", "banke", "deeme", "vncouered", "pound", "thron", "lesse", "churchway", "fairie", "execution",
         "cupids", "locks", "pugging", "deeper", "strife", "intire", "troian", "chides", "merit", "garden", "ryuals",
         "argument", "fiery", "waite", "guilty", "bestow", "helme", "grudge", "oppos", "knaue", "betake", "affliction",
         "sleepers", "prickes", "hoppedance", "anchoring", "ingratfull", "subcontracted", "auncientry", "francklins",
         "swearest", "stande", "chowghes", "mopsa", "slander", "structs", "bents", "banisht", "villaine", "lookes",
         "resolu", "reward", "belongs", "moued", "broke", "champains", "greedinesse", "worships", "wanting", "quiet",
         "astronomicall", "rosted", "speaking", "physicion", "barbarisme", "gossippes", "dignitie", "pursued",
         "prouander", "speedily", "faires", "wronging", "milde", "worne", "changes", "whispering", "orethrow", "honest",
         "influences", "agree", "caterickes", "sloth", "yeeld", "ambition", "farre", "kindle", "headpeece", "betweene",
         "bleaching", "inthrald", "drawne", "scourg", "nurcery", "blast", "churchyards", "perdition",
         "neyther", "warden", "faintnesse", "opposles", "sitting", "would", "deuose", "dally", "fairies", "steeled",
         "lions", "mankind", "prosper", "attended", "damme", "sorely", "staind", "cobwebbe", "wounded", "treasure",
         "turnes", "charracter", "trouble", "honibag", "goard", "esteeme", "neighbour", "became", "shephearddesses",
         "quarta", "stoppe", "vndergoe", "stoops", "throwe", "kniues", "takes", "shoote", "fault", "rising", "woluish",
         "latcht", "whome", "numnesse", "defie", "prayse", "stinck", "realme", "conuenience", "nutes", "veritie",
         "coales", "packs", "diuels", "steele", "hether", "scrippe", "philosopher", "despaire", "tapers", "whelme",
         "greene", "speake", "children", "growes", "learned", "distaffe", "stripes", "obrayds", "centaures", "credent",
         "purpos", "desires", "vnreall", "streme", "openly", "elbows", "vnspoke", "transport", "vvhich", "maister",
         "dwelling", "noone", "manded", "temperance", "greet", "flames", "aydant", "scaped", "sleepe", "safety",
         "heccat", "communicat", "behind", "prouince", "templation", "riots", "bereued", "auowched", "haunt",
         "vntund", "credulous", "saint", "prospers", "dwell", "racks", "walkes", "intention", "weauing",
         "chill", "angell", "potent", "blamelesse", "chafes", "generous", "shame", "scrowle", "apeer",
         "oreweene", "rebell", "solemne", "halter", "whilest", "opposed", "foster", "infirme", "houell", "raised",
         "entrance", "wreath", "insolent", "patrimonie", "lustre", "tigre", "torch", "hasten", "consumation", "scope",
         "odious", "knauish", "lunes", "nurse", "entents", "oppose", "adopted", "rusticke", "wrencht", "forsake",
         "vnbreathed", "suffers", "passes", "bitch", "traitors", "holde", "reuerend", "strangle", "space", "witte",
         "contradict", "assure", "sampire", "saiest", "teasty", "iusticer", "pescod", "shoulder", "receyue", "wrackt",
         "furrow", "fielde", "receiu", "baser", "speedes", "produce", "hungry", "heele", "allowenter", "rashnesse",
         "suffer", "coyning", "split", "deerer", "dances", "smillingly", "creature", "smokes", "witnes", "bandie",
         "traders", "violet", "foure", "wearing", "wrought", "cradle", "answerer", "seuer", "dwarfish", "mungrell",
         "experience", "letter", "foode", "herring", "cushion", "calst", "wages", "hartie", "margent", "calumnie",
         "whitson", "notes", "couples", "dropt", "reuolted", "derides", "eaten", "amends", "amongst", "wenches",
         "cherries", "carefully", "carters", "falsehood", "reioyce", "grace", "forsworne", "content", "sayes", "shrowd",
         "profess", "aspect", "feede", "archidamus", "oracle", "precious", "forgiuen", "happie",
         "fauour", "coster", "nimble", "maruell", "scarse", "shorten", "firme", "tayler", "beautifull", "brake",
         "trespasses", "cures", "midsommer", "swallowed", "bestir", "neare", "pandar", "senselesse",
         "humour", "vulgar", "barricado", "coniunction", "birth", "prethee", "caius", "youle", "mament", "buriall",
         "neighbor", "composition", "sutors", "pilicock", "manhood", "vndistinguishable", "gleeke", "gleaned", "hoast",
         "lacks", "roaring", "reading", "breakes", "complexions", "build", "generall", "country", "creeking", "powers",
         "fables", "march", "rodde", "comest", "cranied", "vvith", "snulbug", "snuffe", "leauen", "fruitful", "russet",
         "dolors", "adamant", "horse", "prizes", "blemishes", "honor", "maufrey", "lower", "deformity",
         "fowle", "satire", "ruffen", "banner", "wakes", "foule", "vnnaturall", "withdrawe", "waight", "separation",
         "reare", "precipitating", "alarums", "exeunt", "weepe", "indure", "cannot", "ginger", "doings", "hooted",
         "blacks", "bedlam", "ladiship", "townes", "squash", "deedes", "offensiue", "beniflicted", "enamourd",
         "stomachers", "condem", "forgiuenesse", "beget", "oppressed", "curtizan", "dride", "troupe", "gentlenesse",
         "gentle", "flowing", "matter", "caparison", "reasonable", "india", "followe", "daffadils", "conceyuing",
         "surplus", "thisby", "trayn", "broad", "rogues", "beauties", "oftner", "cosioner", "merrier", "cryed", "stabs",
         "darker", "seruices", "bitten", "cheeks", "meeting", "impossibilities", "vermine", "fawne", "terror",
         "casting", "iniuries", "guest", "permit", "mannage", "blessed", "quinta", "medler", "needles", "importu",
         "distaffes", "speedie", "rehearsall", "wilfully", "floore", "super", "strip", "bushes",
         "thankefull", "glouster", "function", "rides", "paternall", "tokens", "cheat", "cured", "knaues", "incense",
         "forget", "story", "kingly", "raine", "welkin", "leysurely", "amazed", "harmes", "phrase", "sweat", "vvhen",
         "truthe", "crime", "outface", "slaues", "shift", "necessities", "hyems", "violent", "marchandise",
         "prophanenesse", "imperfection", "poure", "cleeres", "distinguish", "sometimes", "vertue",
         "posternes", "requoyle", "confinde", "falling", "runst", "flours", "heauy", "general",
         "ruffell", "condition", "pittyed", "ceited", "lauender", "approues", "perhappes", "diffiden",
         "wrong", "proclaym", "larke", "reherse", "rumble", "reconciled", "daies", "exalt", "incurre", "perseuer",
         "mended", "hollowd", "begge", "clownes", "throng", "caruers", "golden", "swerue", "bluntnes", "beautious",
         "warpt", "antipodes", "furnishings", "toaze", "recall", "begot", "deaff", "discharge", "prettily", "worse",
         "nicely", "girles", "apparell", "constraineth", "prouision", "garters", "cause", "temper", "swine", "fogges",
         "awake", "honestie", "strike", "vvill", "victory", "milking", "deade", "abuse", "brutish", "wants", "woosell",
         "blown", "contemn", "loose", "briers", "abound", "pottage", "aduanta", "contradicts", "defeated", "fiende",
         "practise", "ballance", "extenuate", "scant", "title", "hoppe", "flowne", "liest", "squint", "disdainefull",
         "sprite", "sunne", "wheele", "ruffe", "chiefe", "strik", "voyce", "vnstate", "dissolue", "pleasant", "monster",
         "maruaile", "stollen", "vanquisht", "couch", "combine", "forme", "altred", "deriu", "tincture", "helens",
         "auant", "crymson", "successe", "shewest", "nimall", "breath", "moones", "alate", "iulyes", "showrs",
         "occupation", "blusters", "intermission", "crack", "rauish", "griffon", "siege", "cowardly", "glost",
         "practises", "euidence", "wench", "newes", "lookers", "distract", "stepdame", "plaid", "conti", "humbling",
         "crownd", "except", "borrow", "forbeare", "constraines", "selues", "bidding", "confound", "sweares", "fashion",
         "taint", "adore", "conceites", "tertius", "buddes", "speedy", "bobtaile", "succession", "thorny", "fathers",
         "cooke", "largest", "cuckow", "bosoms", "powres", "houering", "lobbe", "browes", "pared", "subiect", "bough",
         "humbly", "perswade", "duety", "astray", "viols", "intends", "lyest", "hymnes", "shoot", "leige", "amazons",
         "vilde", "perceau", "lames", "quartus", "deceast", "shady", "reuelles", "slower", "clerkes", "trary", "aright",
         "goddesses", "exasperates", "obserue", "traueled", "organs", "clamorous", "passing", "outside", "tastes",
         "discouerie", "gracefull", "necessary", "counterfeit", "shepherdesse", "procure", "comfort", "catte", "hayld",
         "noyses", "intrench", "aduance", "verse", "storme", "rashnes", "hangs", "sparta", "throttle", "fifteene",
         "intended","deriue", "licenc", "ouerborne", "fould", "plackets", "boyes", "wonder",
         "slacknesse", "inform", "diamonds", "rascals", "abuses", "contriuing", "dutchesse", "ayded", "swaine",
         "soueraintie", "linnen", "knights", "accents", "minimus", "goodly", "portend", "throwne", "knaueries",
         "quarters", "preuaild", "presses", "discarded", "strongest", "walles", "cankers", "sparke", "slips", "maske",
         "murtherous", "thank", "transported", "maladie", "bachanals", "their", "harbour", "centre",
         "borish", "loathsomnesse", "mariorum", "roundest", "carry", "dolefull", "fourescore", "again", "beueridge",
         "conceiue", "gadde", "bewitcht", "beacon", "neighbours", "stables", "bridegroome", "naught", "mocke", "higher",
         "vnhappy", "cornwall", "knitteth", "wrinckles", "generations", "louely", "shifting", "prettyest", "clown",
         "mercurie", "remembrest", "prooue", "moulded", "influence", "recreation", "winke", "donne", "walking",
         "traitorly", "nettles", "coniure", "paramour", "antig", "tyrant", "troll", "poole", "wretched", "loudla",
         "blood", "beames", "wishers", "pardon", "thout", "anchor", "pines", "sparrowe", "lucke", "drawen", "heate",
         "vtters", "discouer", "nesse", "iudging", "buskind", "bemadding", "briefe", "peers", "carpenter", "intreate",
         "howerly", "dream", "thither", "cleanly", "iolly", "wracke", "intent", "wooing", "croppe", "peepes", "snowt",
         "desired", "manifest", "lordings", "euerie", "satisfide", "iaques", "outward", "ently", "kenell", "considered",
         "answere", "altring", "valued", "liuing", "naked", "priuiledge", "kinsman", "perform", "hornes", "thrald",
         "bodie", "ninies", "wedlock", "fraide", "directly", "nighted", "threaten", "vntender", "thankes", "ielous",
         "ground", "knowne", "babes", "pronounce", "vndoe", "gauntlet", "infallible", "resolue", "imployments", "ready",
         "deers", "inheriting", "oldnes", "euill", "sleeue", "mistak", "refus", "bodies", "glosters", "hefts", "guile",
         "forced", "riddle", "puppies", "conceit", "toddes", "iupiter", "ridde", "prouerbe", "motion", "nothing",
         "enterprise", "wilde", "paromord", "kytes", "thanklesse", "beholds",
         "peruse", "fittest", "weedes", "waues", "testimony", "venture", "vnsay", "safer", "doctrine", "crust",
         "blessings", "working", "enclining", "defence", "shrewd", "arraigned", "harlot", "portion", "deptoued",
         "large", "trust", "haile", "hartily", "immodest", "vines", "hardnes", "lodge", "germains", "iealousies",
         "honesty", "shewen", "bellowes", "whistling", "approue", "drowsie", "account", "alarumd", "alter", "hurried",
         "afeard", "patcht", "locall", "heads", "dullest", "holdes", "shortly", "tangled", "shadowe", "triall",
         "diuers", "tumbling", "creepes", "durst", "chappell", "perish", "difference", "require", "nature", "acted",
         "fairy", "deiected", "rauens", "bodyes", "comes", "prethe", "comforting", "mortals", "perswasion", "deuils",
         "pappe", "thanks", "taught", "speare", "bulke", "doore", "iealous", "betrothed", "breach", "marryed",
         "cottage", "bleat", "welcome", "woman", "arrest", "harshnes", "vanitie", "counsails", "silent", "lunatick",
         "withering", "deboyst", "coffe", "depositaries", "bellied", "hedier", "sacrifices", "sterility", "warring",
         "plumed", "profite", "wayes", "brimme", "pearst", "glisters", "ministers", "grunt", "lately", "familiar",
         "pickd", "heere", "south", "billes", "nerely", "lifting", "shadowes", "smalus", "hallow", "counsailor",
         "discrie", "stung", "teame", "sappe", "blink", "heartinesse", "budde", "sonne", "dialogue", "seruise",
         "thrise", "climate", "scattered", "withall", "prescribe", "rounded", "gaoler", "request", "fickle", "prating",
         "pluck", "iollity", "souldiers", "carriage", "danger", "keeper", "frowns", "dowers", "cushings", "coniecture",
         "knauerie", "allot", "liquid", "goddes", "paracides", "reuerbs", "mountaines", "quicker", "truly", "stupid",
         "barbarous", "grauate", "simples", "singing", "mockery", "maide", "interlude", "blind", "booties", "loath",
         "stormes", "valley", "pedler", "sharpest", "plainnes", "venome", "hooke", "bleated", "blister", "gaping",
         "foord", "bogge", "malady", "gossips", "stoode", "proclamations", "bagges", "retire", "coulde", "newer",
         "penne", "twinckled", "braine", "gouernd", "greetings", "longing", "posture", "womans", "boote", "auoid",
         "robbers", "affects", "coyne", "wishing", "prediction", "tolde", "crescent", "condemn", "eyeliddes", "coronet",
         "danke", "vnmarried", "sepulchring", "burne", "sighted", "sawcy", "surgeon", "whisper", "colte", "beshrewe",
         "iniurious", "dumbe", "burgomaske", "stirring", "measure", "carre", "kings", "questrits", "thirtie",
         "preuailement", "sectary", "middle", "hotter", "melted", "nedars", "states", "freshest", "excuse", "bewaile",
         "biting", "straight", "importance", "festiuall", "prison", "mounch", "carroll", "mischiefe", "attendants",
         "ethiop", "tweene", "modest", "tosse", "coppy", "faith", "buies", "hatch", "profits", "bleed", "quickly",
         "forked", "choghes", "natiuitie", "betwixt", "serue", "deceaued", "markt", "beholder", "crost", "triumphantly",
         "psalmes", "surge", "antique", "feeders", "radient", "foppery", "stubburne", "mamillus", "holpt",
         "predominant", "shocks", "grapes", "flashes", "expiration", "ciuet", "glistering", "waspes", "loosing",
         "replyed", "channels", "paires", "suppos", "entreatie", "slowly", "easterne", "shewes", "banes",
         "lights", "folow", "followes", "tardied", "sinning", "manly", "second", "reporting", "swithald", "weaknes",
         "apothocarie", "vvhat", "couering", "heardsmen", "brauely", "subscribd", "shrieke", "vvhose", "fouler",
         "drunckards", "foolery", "heauings", "stratagem", "ordering", "worser", "shippe", "fixure", "dorcas", "vrgent",
         "gasping", "accompt", "dismantell", "vnfriended", "heres", "absence", "vnkind", "scarcely", "legitimate",
         "nosthrill", "gelly", "dungy", "purgation", "centurie", "sulphury", "suited", "attempting",
         "something", "talke", "watcht", "badnes", "bottome", "bloes", "mowse", "viewe", "simple", "primrose",
         "purport", "alack", "mother", "circumference", "villaines", "spreade", "washt", "eldest", "excellence",
         "welcom", "roule", "prayses", "whers", "qualified", "commaunds", "porter", "threatens", "heresies", "spight",
         "tyrannie", "vanisht", "repose", "greeuing", "fortunate", "pities", "crazed", "warbling", "labouring",
         "preserued", "spirits", "heretofore", "sighes", "gates", "heretiques", "euent", "reignes", "liege", "graunt",
         "sooner", "industriously", "filths", "weary", "faiery", "millions", "condole", "steeples", "fingers", "munger",
         "saile", "redeem", "coniealed", "simply", "barraine", "afraid", "sorting", "qualities", "infirmities", "hides",
         "compounded", "vnvsuall", "stops", "diuision", "white", "refuse", "patiently", "glance", "moity", "ruslings",
         "answerd", "loyalty", "crown", "hadst", "tryall", "kinsmans", "ceremony", "hootes", "clouds", "hurts",
         "another", "confest", "countrie", "imploy", "nisely", "inuades", "implore", "allegeance", "hould", "remainder",
         "lanthorne", "deseruings", "marching", "gayle", "pilfrings", "exposd", "snake", "feelingly", "needlesse",
         "panting", "distant", "materiall", "raineth", "vngratious", "fauorable", "promis", "fright", "dearely",
         "groue", "patches", "longs", "nations", "leaue", "mornings", "apprehension", "champion", "endur", "boldly",
         "commit", "mechanicals", "washes", "retyred", "branches", "audience", "builds", "perseuere", "enfoldings",
         "faery", "vndivulged", "marie", "vnwished", "charmeth", "father", "visions", "vnprizd",
         "soiournd", "markes", "betrayes", "mightst", "tromperie", "varying", "shades", "shouels", "blamefull",
         "forewarne", "whats", "remotion", "ingratful", "pitie", "dimples", "camulet", "vsurpt", "forswear", "staine",
         "trice", "knowe", "write", "dewberries", "shall", "preuented", "taunted", "wings", "monsier", "slaue",
         "doodla", "sting", "checkes", "plagues", "scowre", "lippe", "weaknesse", "prayers", "glory",
         "suggestion", "heades", "pension", "iniquitie", "cloyster", "preheminence", "swifter", "lamenes", "tempting",
         "peter", "thats", "ioyne", "deere", "suspects", "conferre", "proceed", "busie", "naturally", "theame", "beast",
         "wombe", "ceremonious", "miserable", "about", "vnlesse", "while", "praysed", "bolted", "crutches",
         "sternnesse", "caues", "vnusuall", "circumstances", "entise", "neerely", "birds", "bloudyhand", "teeme",
         "harmfull", "tatling", "monky", "translated", "deeply", "patience", "hinde", "swallow", "vnconstant",
         "inraged", "appeares", "strumpet", "bowget", "farewell", "prise", "thought", "villages", "minister", "quired",
         "cruels", "iustifie", "burnt", "stewd", "furnish", "score", "heauier", "canker", "eyebals", "professions",
         "throwest", "hinders", "throned", "vnpossessing", "parson", "guests", "sitie", "verie", "mankinde", "lenders",
         "retention", "conuenient", "secret", "plaine", "detecter", "ought", "pursu", "greedines", "childe",
         "hermiones", "along", "slumbred", "beene", "nineteene", "anothers", "dated", "stock", "singer", "hoxes",
         "coragiously", "meete", "failes", "pledge", "baggage", "hearted", "wanst", "framed", "enforced", "riuer",
         "toldst", "inuested", "fayth", "mulberries", "burie", "sunder", "adultery", "toads", "loathly", "furies",
         "conditions", "minds", "sinke", "informed", "burgundy", "ripenes", "flourish", "heart", "chaunting",
         "cornewall", "flower", "imagining", "maledictions", "ensue", "spent", "wearers", "armes", "should", "rackles",
         "honorable", "appeale", "eunuche", "gallerie", "constant", "peascod", "arriuall", "bleedes", "employ",
         "stopping", "dayes", "eclipses", "vengeances", "certaine", "chace", "saddest", "swaines", "dearne", "spies",
         "priuy", "tawdry", "contending", "pelicane", "ingag", "makes", "continent", "violation",
         "aduancement", "sheepe", "warlike", "necessarie", "aught", "excre", "lothed", "withered", "pretty", "worlde",
         "anoynted", "noise", "qualifie", "slights", "chide", "bessy", "things", "bawdrie", "arraigne", "clymat",
         "interchang", "leasure", "foppish", "remorse", "queen", "friendship", "condo", "meaning", "thence", "swimming",
         "lifes", "busines", "milles", "dealing", "bread", "siluer", "passion", "deuourd", "purple", "followers",
         "loosest", "cleomines", "promised", "toppe", "purpost", "lawyer", "killes", "crowne", "compasse", "skippe",
         "eyther", "prefix", "shines", "intirely", "gawdes", "liuer", "heraldry", "emilia", "spangled", "comforts",
         "harme", "greete", "tould", "friendshippe", "sorow", "simplicity", "blasts", "lodging", "stare", "docks",
         "beteeme", "remembrance", "smartly", "vnsafe", "fancies", "bould", "vnlawfull", "making", "great", "pander",
         "indeuour", "forcing", "vvinde", "thrust", "blindewormes", "clamor", "begetting", "courtier",
         "downeright", "relation", "watry", "likenes", "tedious", "company", "criticall", "dying", "reckon",
         "pilgrimage", "common", "fiends", "inuade", "sleepest", "wherefore", "attending", "iustices", "gratious",
         "paued", "blacker", "caytife", "vnfould", "laughs", "releeue", "comst", "gotte", "custome", "waits", "flaxe",
         "fountaines", "shooe", "ended", "hindring", "hobbididence", "maisters", "fighter", "yeeres", "weare",
         "vnsanctified", "toucht", "iouiall", "vowes", "gessingly", "often", "locke", "frosts", "places", "proceede",
         "feareful", "germanie", "vnkindnesse", "tance", "swels", "queues", "wormy", "dumbly", "sphery", "centers",
         "within", "bodkins", "merriments", "taile", "whorson", "moneths", "pipes", "vulgars", "insuffi", "herald",
         "fitted", "powerfull", "couered", "seuen", "deseruing", "reuolt", "message", "promise", "meruaile", "orerules",
         "renounce", "murther", "satisfie", "encounter", "sommer", "chargd", "choyce", "ariues", "adheres", "seruants",
         "arrant", "crooke", "albanies", "sennet", "perused", "pawse", "philomele", "athens",
         "language", "respects", "woodbine", "leade", "laugh", "fourteene", "affright", "saued", "politike", "minutes",
         "fadomes", "colder", "blanke", "wolfe", "finger", "ryotous", "sheene", "manager", "arriue", "spread", "endure",
         "stopt", "betray", "notion", "certaintie", "netles", "wheate", "moneth", "perhaps", "assur", "darken", "arrow",
         "odorous", "gentlemanlike", "frowne", "circled", "homely", "condemne", "enemy", "hammered", "cheare", "hoods",
         "periods", "weeping", "fellowshippe", "otherwise", "conspiring", "poets", "reform", "fertile", "confine",
         "pittied", "doubted", "reade", "proper", "choller", "freer", "night", "hogge", "essay", "illustrious",
         "kerchief", "sophisticated", "versing", "smackes", "indeed", "madam", "slowe", "sweeter", "ample", "gloster",
         "oretake", "lysanders", "wearest", "proserpina", "third", "slightly", "reach", "consecrate", "breathes",
         "fares", "error", "sence", "yeelde", "harshnesse", "murmuring", "fastned", "maiden", "scena", "diligent",
         "progno", "stronger", "moues", "declining", "resort", "pageant", "ruddinesse", "noynted", "bittrest", "befall",
         "bracelets", "balme", "thoughts", "phangs", "grosse", "infected", "spare", "bethinke", "princely",
         "cemicircle", "leape", "virginalling", "forsweare", "ships", "beguild", "ribands", "erres", "spectators",
         "disgrace", "quarrell", "gently", "alapt", "craues", "firmament", "bestowed", "fathom", "beleeu",
         "shrewishnesse", "passio", "rankt", "matcht", "shaking", "natures", "change", "diminisht", "purses", "merry",
         "proofe", "reports", "tawyer", "frights", "mistrisse", "necke", "requires", "burnd", "performed", "authoritie",
         "discerne", "nunckle", "conueyd", "plainely", "issue", "holds", "thicker", "painted", "speedely", "crawling",
         "doctor", "blinding", "addition", "affaires", "dagger", "frequent", "cornewell", "cockes", "consideration",
         "tricks", "painting", "idlenesse", "warpe", "imperfect", "concealement", "coxcombe", "publique", "bohemia",
         "cliffe", "eloquence", "lucky", "famous", "shrugs", "boasts", "leane", "counts", "proposd", "truest", "sects",
         "growing", "gaude", "tooke", "leash", "fellowes", "summons", "seale", "kneele", "peares", "dulcet", "sweete",
         "earely", "quick", "recount", "deseru", "rarely", "comfortable", "twould", "molten", "captiues", "kindred",
         "claime", "perso", "enclosed", "abdication", "hested", "colde", "doubtfull", "pinched", "aunts", "deliuered",
         "sound", "perfume", "wombed", "oprest", "mightily", "equally", "signifie", "maior", "masters", "faining",
         "wisest", "mooneshine", "pence", "grange", "plaint", "mercie", "togither", "sooth", "skulking", "partlet",
         "publish", "thessalian", "deuoure", "diuided", "varie", "infects", "friendshippes", "coates", "vnsettle",
         "seeing", "droppe", "mortall", "vnroosted", "proclamed", "beasts", "wanted", "proclaymes", "leuied", "gownes",
         "parasite", "fabrick", "yealds", "rents", "filth", "halcion", "suffering", "roard", "impute", "whilst",
         "troth", "trumpet", "ranke", "series", "indistinguisht", "groues", "quite", "deceiue", "summond", "primus",
         "stockes", "widow", "morall", "reseruation", "dates", "madded", "visage", "spices", "future", "cowish",
         "forgiuenes", "marrying", "auntient", "roared", "paths", "departure", "rehearse", "spouts",
         "lecherous", "practised", "rather", "alexander", "pluckt", "cords", "rolling", "woulde",
         "kernell", "exploit", "lippes", "mannerly", "gonorill", "queint", "gosmore", "burnes", "damne", "sharper",
         "loftie", "accompany", "hasting", "crush", "memorie", "personage", "mirror", "breeds", "brought", "theeues",
         "knees", "praysd", "nymph", "place", "remedy", "enforst", "stones", "intreatie", "health",
         "assurance", "impatient", "maides", "tickle", "session", "machinations", "vassall", "shell", "clout", "incht",
         "colours", "attend", "cheese", "grones", "growe", "goest", "thanke", "peerelesse", "lasting", "climing",
         "weather", "punishment", "sorowes", "blots", "knowest", "rigor", "signior", "barber", "hobgoblin", "stealing",
         "print", "seeking", "thorne", "flute", "sports", "incurd", "intend", "sensible", "trayne", "proclaim", "vsage",
         "verely", "partition", "kneeles", "tooth", "compare", "sport", "mildnes", "flies", "superflux", "conspicuate",
         "diseas", "putter", "euery", "combate", "croane", "seldome", "checke", "ranks", "twixt", "roome",
         "countenance", "walls", "churches", "transfigur", "commandment", "fadings", "mistaking", "amazd", "iacke",
         "sampler", "cleft", "therefore", "infectious", "adornes", "innocence", "nutmegges", "wicked", "grizly",
         "suffice", "troubles", "glowe", "marriner", "welcomes", "whipt", "swoune", "lifted", "momentany", "maiestie",
         "salutations", "quesie", "frame", "plaster", "region", "preuent", "image", "margerum", "confidence",
         "vnbraided", "ouercast", "crying", "playfellow", "rubies", "inuisible", "lamentably", "turne", "iewels",
         "cruell", "softly", "society", "secundus", "midway", "brest", "shiuering", "dames", "spartane", "dianaes",
         "gaine", "contrary", "enemie", "curan", "bolde", "batcheler", "starts", "nights", "accesse", "sister",
         "allowing", "iuggler", "flowres", "shining", "beautie", "lanterne", "discontenting", "vntill", "pelicocks",
         "subdued", "courts", "ghosts", "disguise", "wrongs", "enform", "venus", "hisse", "pleas", "bitte", "report",
         "canst", "formes", "spout", "friendes", "challenge", "noble", "imbossed", "occasion", "course", "brewers",
         "miles", "forrester", "thereby", "booke", "leading", "wheat", "prodigious", "currers", "desarts", "effect",
         "bergomaske", "sometime", "pockets", "frighted", "deepe", "amason", "warres", "messengers", "impossible",
         "collied", "lozell", "football", "afflict", "present", "climbe", "lambs", "bellowed", "oaths", "weaues",
         "persecution", "blouded", "assume", "begger", "barne", "proud", "challengd", "attach", "spring", "farthell",
         "among", "preposte", "dissembling", "gallant", "render", "glasse", "feeling", "magick", "lulla", "aliue",
         "repreeue", "vpper", "coniuring", "faults", "indignation", "besides", "breeding", "lytter", "sully", "chanc",
         "knackes", "negatiue", "reuengiue", "quicke", "owning", "fortie", "practis", "vnfitnesse", "vnruly", "suffici",
         "mingling", "braynes", "inconstant", "tongu", "tother", "charges", "stander", "beheld", "roses", "disordred",
         "ouercanopi", "vnwhipt", "redeemes", "vnfledg", "bated", "dispaire", "kents", "mistaketh",
         "toward", "diuorce", "incapeable", "cookow", "belly", "directing", "marrie", "follow",
         "chalkie", "chaynes", "sleeping", "whites", "vestall", "ashamed", "foxes", "births", "affectio", "lowse",
         "shund", "beare", "minded", "vntride", "quantitie", "runne", "forbearance", "distild", "edict", "sauagenesse",
         "goblin", "appeare", "tithing", "summer", "powrefull", "languish", "contagious", "guilts", "floute", "couer",
         "gallow", "sweare", "seemed", "counsail", "grasse", "beastes", "brakes", "peeble", "morter", "inuest",
         "fatted", "maine", "amities", "notwithstanding", "sixteene", "victor", "speeches", "liuerd", "voyage", "folly",
         "ladde", "lancht", "finisht", "songget", "diuide", "times", "compters", "smugge", "changeling", "hardning",
         "herds", "strokes", "cloath", "barbers", "telling", "stray", "married", "tortures", "dainty",
         "beach", "hymne", "physick", "sutes", "shade", "fruits", "maist", "artificiall", "lysand",
         "conuerse", "shepherd", "mockst", "charmes", "rises", "reskue", "valour", "pricke", "hopefull", "anger",
         "waued", "ouerruld", "order", "doues", "lawfull", "horror", "contemnes", "statue", "hiszing", "soyled",
         "twaine", "indictment", "opportunities", "rounds", "varlot", "graund", "therwithal", "bookish", "seruiceable",
         "vulture", "brier", "manifold", "masterly", "propinquitie", "trowest", "remediat", "gorgeous", "depriu",
         "tosted", "prisoners", "fight", "attractiue", "lowder", "sword", "distresse", "quitted", "oyster", "pittiles",
         "begin", "vndescry", "gyant", "answeres", "planet", "lingring", "growth", "northerne", "wiues", "hircanios",
         "sheel", "singe", "seekes", "likenesse", "mastife", "scurrilous", "extreame", "seemd", "derogate", "eleuen",
         "swagg", "marking", "accusers", "counsels", "stabbing", "accurs", "breast", "conceale", "conscience",
         "dangers", "vantage", "glaunce", "weele", "strangely", "loues", "confirming", "ruind", "sustaine", "modesty",
         "ploughman", "florizel", "bright", "perishing", "helpe", "spouse", "indured", "wooll", "remou", "soften",
         "offended", "wrappe", "amplifie", "whole", "regard", "outrage", "beane", "confirm", "glimmering", "dwarfe",
         "prest", "seconds", "crany", "consents", "prosperitie", "deuill", "excells", "vitious", "morrow", "whereat",
         "imployment", "iustification", "auailes", "turned", "singularities", "disuetur", "vnsubstantiall", "cleane",
         "concord", "election", "whoreson", "dramatis", "reuenged", "wither", "forfended", "ruinous", "foorth",
         "meating", "vnaccomo", "french", "crabbe", "dandy", "guiltie", "vnfortunate", "parings", "goodnight",
         "conflicting", "property", "criminall", "diuides", "solus", "dukes", "hercules", "forgiue",
         "seeming", "slept", "orient", "priest", "mightie", "choice", "mohing", "credit",
         "curteous", "bethought", "deserued", "humbled", "poysons", "vntimely", "engilds", "watrish", "silken",
         "starue", "wifes", "kindnesse", "swaies", "bottle", "inioy", "seest", "burthen", "epilogue", "supposed",
         "plight", "beleeue", "fanne", "treason", "againe", "chauntes", "felicitate", "conference", "valiant",
         "nightin", "tenne", "fellow", "incline", "caese", "receaued", "silliest", "crawle", "berries", "palace",
         "deficient", "behalfe", "childing", "fortunes", "sines", "sanded", "knauery", "quakes", "lighter", "feirce",
         "weild", "dares", "epicurisme", "originall", "goblins", "stretcht", "outwardly", "repaire", "quality",
         "different", "attaint", "dissolutions", "exsist", "swell", "policie", "doricles", "proclaimd", "quart",
         "enrings", "medull", "misgraffed", "pastorals", "creeping", "examine", "sinnes", "mistake",
         "shriekes", "physitian", "spoken", "stalles", "adder", "imprisoned", "inclining", "straited", "ninnies",
         "mistooke", "bring", "virgine", "foulds", "vsurps", "swallowes", "ballads", "roofes", "bornet", "furre",
         "beefe", "burst", "trueth", "countrey", "kneed", "obligation", "offring", "motley", "countries", "conclude",
         "feather", "mints", "basilisque", "odour", "remembred", "scanted", "crowned", "horsing", "iourney",
         "conquerour", "hasty", "kisse", "helena", "driue", "skyes", "truer", "follyes", "deaths", "worlds", "whence",
         "stople", "carefull", "learning", "catching", "horses", "improper", "distemperature", "requir", "garment",
         "schooldaies", "demanded", "master", "bound", "hospitable", "blisse", "found", "labour", "coxcombes", "birde",
         "interpose", "behauiour", "beyond", "officers", "conquerer", "auroras", "bladed", "still", "value", "iowle",
         "phibbus", "snapper", "worthy", "iarre", "threw", "smoyle", "arbiterment", "clock", "extempore", "feasting",
         "shores", "whore", "inflam", "indispos", "pillow", "reuiues", "clouest", "sunny", "verball", "copulation",
         "childed", "authority", "standst", "lingers", "displease", "onions", "season", "disbranch", "villanous",
         "ladyes", "deities", "offence", "perforce", "center", "running", "libertie", "nourish", "dreads", "swaruer",
         "sayest", "store", "capacity", "protestation", "chang", "rehearst", "discredits", "embracement", "partiall",
         "irremoueable", "thing", "thrice", "hollow", "amazednesse", "rotten", "boylde", "lidde", "crackt", "truth",
         "vnfurnish", "driuen", "thriue", "youngest", "retaine", "nayles", "button", "vpbraid", "drunke", "chase",
         "choise", "recompenc", "superstition", "wretch", "societie", "deerely", "leadings", "flouriets", "followres",
         "freckles", "goades", "riuers", "boast", "foundation", "vision", "boores", "fragrant", "wrath", "shees",
         "happily", "lethergie", "reply", "thunderboults", "starlight", "goodnes", "likes", "moales", "mercy",
         "fortnight", "ouerheare", "league", "instigation", "filthie", "midwiues", "setting", "rouer", "finis", "thump",
         "sorry", "draught", "dutches", "imediate", "soone", "throwing", "pensioners", "promontory", "kinde",
         "vnderstand", "shunne", "dieted", "darkling", "assisted", "disiunction", "saies", "euilles", "recouer",
         "pardons", "pluckes", "sprindge", "paradise", "awhile", "spirite", "period", "temporizer", "herein", "payes",
         "tribe", "dependants", "processe", "badge", "squire", "ignorant", "vertuous", "seene", "venge", "lears",
         "disgrac", "shield", "determine", "mountaine", "shoute", "earth", "oddes", "shilling", "tardines", "token",
         "performde", "diuinitie", "command", "auouch", "hindg", "miserie", "feathers", "bloudy", "standing", "voice",
         "support", "knowing", "dittie", "yours", "thorough", "needfull", "diseases", "comprehends", "mongst", "cheape",
         "acheron", "cursses", "straied", "stayne", "antipathy", "garlick", "confined", "stayeth", "heretique",
         "redres", "ports", "attire", "vexes", "tarying", "tittle", "bridges", "fishermen", "franke", "strings",
         "following", "vnmannerly", "spits", "apply", "neptunes", "quarrels", "choughes", "hearbe", "parrell",
         "foundations", "swore", "craue", "waggish", "ransome", "alters", "guardians", "vnitie", "commitst", "strength",
         "bolds", "oates", "vsuall", "cherne", "pyramus", "shrowde", "direction", "knell", "autums", "addresse",
         "spill", "prettie", "followed", "chaste", "nursing", "shalt", "gonoril", "rapier", "expedition", "beggery",
         "russel", "silly", "sparrow", "impudence", "taylerrepresenting", "rauen", "violently", "palme", "fortune",
         "pleasures", "sustayning", "throne", "auert", "dreames", "promising", "flayd", "peart", "peace", "lethren",
         "trecherers", "cozen", "ruffines", "pearcing", "piercing", "anguish", "toyes", "ghost", "louers", "flaying",
         "partie", "shrew", "nightwanderers", "degree", "companie", "decking", "dience", "bloudie", "vallie",
         "bootelesse", "quince", "sieur", "deuen", "vnspeakable", "woundings", "mustardseede", "waies", "compell",
         "ragges", "teare", "power", "herbe", "abilitie", "rageth", "apase", "bruse", "hereditarie", "studie",
         "greatest", "dwelt", "bolder", "tyrannous", "heauen", "trippingly", "footman", "gyantlike", "dismiss",
         "aweary", "basest", "gilly", "cobweb", "couerd", "vnworthy", "deale", "history", "sparks", "hunting", "taurus",
         "persian", "inloose", "house", "awaking", "marted", "sought", "reine", "farther", "transpose", "deuis",
         "lawne", "affection", "opening", "profession", "shallow", "partly", "breed", "declare", "twill", "affirme",
         "clowne", "afoot", "points", "disdainfull", "britain", "assured", "ladie", "blinde", "soundest", "bagger",
         "commended", "dishonor", "reuels", "perceiue", "petty", "childhood", "vnkindly", "tragicall", "wildest",
         "wrongd", "slight", "sailes", "alreadie", "bootlesse", "hourly", "boldnesse", "sharpe", "blows", "restrayning",
         "concernes", "angling", "sickly", "cheuore", "stealth", "soueraigne", "corps", "superfluous", "extreamitie",
         "playd", "certainely", "hauing", "importune", "betters", "colouring", "intreat", "skinne", "snuffes",
         "perpetuall", "mounsieur", "surfet", "comforted", "neers", "wretchednesse", "wherin", "safetie", "caught",
         "leontes", "deserue", "tongue", "meant", "faile", "bluntly", "skirted", "ledge", "supper", "speede",
         "enduring", "arayd", "iudge", "beniz", "faire", "appoint", "iollitie", "shooke", "windowe",
         "solemnities", "polixenes", "dislike", "corin", "faster", "merriment", "trunke", "forth", "quill", "learn",
         "saddle", "blushes", "disturbd", "mindes", "shalbe", "houill", "dinner", "clocks", "monsters", "ignoble",
         "whispring", "empty", "wealth", "defect", "mistrusted", "collop", "breech", "orange", "inuention", "sicilian",
         "obseruation", "cagion", "bedde", "point", "finding", "benediction", "seruant", "steward", "burthens",
         "admiration", "equalities", "flowry", "obscur", "passe", "riuals", "hoary", "expectation", "bleak",
         "throughly", "bearde", "repayre", "roges", "thine", "accidents", "encounters", "suddenly", "fraught",
         "aduantage", "puritie", "friends", "december", "remaine", "liberty", "medicinall", "speciall", "heares",
         "outscorne", "prety", "proselytes", "whipst", "diuisions", "prologue", "seaze", "epeliptick", "trembling",
         "theban", "fichew", "tends", "enfranchis", "thereon", "terrible", "yonder", "flora", "hastie", "reuenues",
         "maskes", "sirra", "soules", "discreet", "interpreters", "spende", "madnesse", "comrade", "newts", "defile",
         "silence", "mistaken", "vngouernd", "fights", "eyles", "stuffe", "threes", "listen", "reconcile", "allwaies",
         "habit", "words", "humor", "laughing", "thirst", "sorrowed", "lusts", "spirituall", "scuruy", "cience",
         "keepes", "feares", "study", "curled", "delicate", "cowards", "fretereto", "stake", "whirle", "iointly",
         "hallowed", "lamentable", "beguile", "ingratefull", "exchange", "confounding", "neither", "gentleman",
         "ancient", "couragious", "meaner", "wanton", "cohorts", "xtreamest", "whoremaster", "strew", "snores",
         "throat", "gouernement", "curiositie", "braines", "disdaine", "treats", "verge", "seasons", "nobler",
         "firmely", "buyer", "angring", "waiting", "market", "resides", "restrained", "superpraise", "presence",
         "elder", "mourning", "vnthriftie", "earnest", "heyre", "lunaticke", "riuald", "turtles", "palmes", "heire",
         "confederacy", "sneaping", "leake", "compos", "arraine", "plucke", "charg", "disswaded", "toumbe", "clear",
         "straining", "enamoured", "selfe", "treachery", "mates", "goodnesse", "cackling", "pumpes", "trades",
         "mistresses", "femiter", "watches", "dreadful", "redresse", "garlands", "entertainment",
         "shallowest", "hermonious", "thwack", "additions", "musicke", "borrowed", "actes", "commission", "rogue",
         "anchors", "recompence", "winde", "bride", "throwes", "receiues", "cordis", "liuely", "bloud", "abide",
         "plainsong", "opposites", "darnell", "athenians", "wickednes", "festuant", "winters", "ponderous", "gloabe",
         "breathlesse", "shares", "sharpes", "latter", "acknowledged", "miscaried", "royaltie", "sweeten", "lullaby",
         "degrees", "euerlasting", "ouerwatcht"]


def generate_captcha():
    word = WORDS[random.randrange(0, len(WORDS))]

    image = Image.new('RGB', (300, 50), color=(255, 255, 255))
    font = ImageFont.truetype(FONT, 50)
    draw = ImageDraw.Draw(image)
    draw.text((0, 0), word, font=font, fill=(231, 37, 42))
    buffer = BytesIO()
    image.save(buffer, format="PNG")
    base64_string = base64.b64encode(buffer.getvalue()).decode('utf-8')

    word_hash = hashlib.sha1(str.encode(word))
    word_hash = word_hash.hexdigest()

    return base64_string, word_hash


def validate_captcha(word, hash):
    word_hash = hashlib.sha1(str.encode(word))
    word_hash = word_hash.hexdigest()

    return hash == word_hash
